import { Archive, CalendarDays, ChevronDown, Database, Download, Eye, FileText, Filter, FolderOpen, MoreVertical, RefreshCw, X } from "lucide-react";
import { CheckBox } from "../../shared/ui/CheckBox";
import { PageFrame } from "../../shared/ui/PageFrame";
import { PageTitle } from "../../shared/ui/PageTitle";
import { SearchInput } from "../../shared/ui/SearchInput";
import { Stat } from "../../shared/ui/Stat";

const reports = [["Рапорт на відпустку – Іваненко І.І.", "Рапорт на відпустку", "1", "27.07.2026 12:45"], ["Рапорт на матеріальну допомогу – 3 особи", "Рапорт на матеріальну допомогу", "3", "27.07.2026 11:20"], ["Рапорт на зміну місця служби – Шевченко Т.Г.", "Рапорт на зміну місця служби", "1", "27.07.2026 10:05"], ["Рапорт на відрядження – 2 особи", "Рапорт на відрядження", "2", "26.07.2026 18:30"], ["Рапорт на звільнення – Кравчук О.П.", "Рапорт на звільнення", "1", "26.07.2026 16:12"]];

export function GeneratedReportsPage() { const tools = <section className="panel generated-filters"><SearchInput placeholder="Пошук рапортів…" /><button className="button"><Filter />Фільтри <ChevronDown /></button><label>Період<input value="01.07.2026 – 27.07.2026" readOnly /></label><label>Шаблон<button className="select">Усі шаблони <ChevronDown /></button></label><label>Сортування<button className="select">Дата: нові спочатку <ChevronDown /></button></label><div className="quick-filter">{["Усі", "Сьогодні", "Вчора", "За тиждень", "За місяць"].map((name, index) => <button key={name}>{name} <b>{[48, 5, 8, 27, 48][index]}</b></button>)}</div></section>; return <PageFrame header={<PageTitle title="Згенеровані рапорти" subtitle="Список усіх згенерованих рапортів" actions={<><button className="button"><RefreshCw />Оновити</button><button className="button"><Download />Експорт списку</button><button className="button primary"><FolderOpen />Відкрити папку з рапортами</button></>} />} tools={tools} footer={<div className="statbar"><Stat icon={Archive} label="Усього рапортів" value="48" /><Stat icon={CalendarDays} label="Згенеровано сьогодні" value="5" /><Stat icon={CalendarDays} label="За тиждень" value="27" /><Stat icon={CalendarDays} label="За місяць" value="48" /><Stat icon={Database} label="Обсяг файлів" value="18.7 MB" /></div>} className="generated-page"><div className="generated-layout"><section className="panel data-table"><div className="data-table__scroll"><table><thead><tr><th><CheckBox /></th><th>Назва рапорту</th><th>Шаблон</th><th>Кількість осіб</th><th>Дата генерації ↓</th><th>Дії</th></tr></thead><tbody>{reports.map(([name, template, count, date], index) => <tr className={index === 0 ? "selected-row" : ""} key={name}><td><CheckBox /></td><td><span className="word-icon">W</span>{name}</td><td>{template}</td><td>{count}</td><td>{date}</td><td><button className="icon-button"><Eye /></button><button className="icon-button"><FolderOpen /></button><button className="icon-button"><MoreVertical /></button></td></tr>)}</tbody></table></div><div className="pagination">Показано 1–10 із 48 <span>‹ <b>1</b> 2 3 4 5 … ›</span></div></section><aside className="panel report-details"><button className="close"><X /></button><h2>Рапорт на відпустку – Іваненко І.І.</h2><p><span className="word-icon">W</span> DOCX · 42.1 KB</p><small>Шлях:<br />C:\Reports\2026\07\27\Рапорт_відпустка.docx</small><div className="actions-line"><button className="button primary"><Eye />Відкрити</button><button className="button"><FolderOpen />Відкрити папку</button></div><h3>Інформація</h3><dl><dt>Шаблон:</dt><dd>Рапорт на відпустку</dd><dt>Кількість осіб:</dt><dd>1</dd></dl></aside></div></PageFrame>; }
