import { useMemo, useState } from "react";
import { Archive, CalendarDays, Database, Download, Eye, FileText, FolderOpen, MoreVertical, RefreshCw, X } from "lucide-react";
import { CheckBox } from "../../shared/ui/CheckBox";
import { FilterButton } from "../../shared/ui/FilterButton";
import { PageFrame } from "../../shared/ui/PageFrame";
import { PageTitle } from "../../shared/ui/PageTitle";
import { SearchInput } from "../../shared/ui/SearchInput";
import { Select } from "../../shared/ui/Select";
import { Stat } from "../../shared/ui/Stat";
import { includesSearch } from "../../shared/utils/search";

type Report = { name: string; template: string; people: number; date: string };
const reports: Report[] = [{ name: "Рапорт на відпустку – Іваненко І.І.", template: "Рапорт на відпустку", people: 1, date: "27.07.2026 12:45" }, { name: "Рапорт на матеріальну допомогу – 3 особи", template: "Рапорт на матеріальну допомогу", people: 3, date: "27.07.2026 11:20" }, { name: "Рапорт на зміну місця служби – Шевченко Т.Г.", template: "Рапорт на зміну місця служби", people: 1, date: "27.07.2026 10:05" }, { name: "Рапорт на відрядження – 2 особи", template: "Рапорт на відрядження", people: 2, date: "26.07.2026 18:30" }, { name: "Рапорт на звільнення – Кравчук О.П.", template: "Рапорт на звільнення", people: 1, date: "26.07.2026 16:12" }];

export function GeneratedReportsPage() {
  const [query, setQuery] = useState(""); const [filtersOpen, setFiltersOpen] = useState(false); const [template, setTemplate] = useState("all"); const [sort, setSort] = useState("new");
  const templates = useMemo(() => [...new Set(reports.map((report) => report.template))], []);
  const filtered = reports.filter((report) => (template === "all" || report.template === template) && includesSearch(query, report.name, report.template)).sort((left, right) => sort === "new" ? right.date.localeCompare(left.date) : left.date.localeCompare(right.date));
  const tools = <section className="panel generated-filters"><SearchInput placeholder="Пошук рапортів…" value={query} onChange={setQuery} /><FilterButton active={filtersOpen} onClick={() => setFiltersOpen((current) => !current)} />{filtersOpen && <><Select ariaLabel="Фільтр за шаблоном" value={template} onChange={setTemplate} options={[{ value: "all", label: "Усі шаблони" }, ...templates.map((item) => ({ value: item, label: item }))]} /><Select ariaLabel="Сортування рапортів" value={sort} onChange={setSort} options={[{ value: "new", label: "Дата: нові спочатку" }, { value: "old", label: "Дата: старі спочатку" }]} /><button className="button" onClick={() => { setQuery(""); setTemplate("all"); setSort("new"); }}>Скинути</button></>}<div className="quick-filter"><button>Усі <b>{filtered.length}</b></button></div></section>;
  return <PageFrame header={<PageTitle title="Згенеровані рапорти" subtitle="Список усіх згенерованих рапортів" actions={<><button className="button"><RefreshCw />Оновити</button><button className="button"><Download />Експорт списку</button><button className="button primary"><FolderOpen />Відкрити папку з рапортами</button></>} />} tools={tools} footer={<div className="statbar"><Stat icon={Archive} label="Усього рапортів" value={reports.length} /><Stat icon={CalendarDays} label="Згенеровано сьогодні" value="0" /><Stat icon={Database} label="Обсяг файлів" value="—" /></div>} className="generated-page"><div className="generated-layout"><section className="panel data-table"><div className="data-table__scroll"><table><thead><tr><th><CheckBox /></th><th>Назва рапорту</th><th>Шаблон</th><th>Кількість осіб</th><th>Дата генерації ↓</th><th>Дії</th></tr></thead><tbody>{filtered.map((report, index) => <tr className={index === 0 ? "selected-row" : ""} key={report.name}><td><CheckBox /></td><td><span className="word-icon">W</span>{report.name}</td><td>{report.template}</td><td>{report.people}</td><td>{report.date}</td><td><button className="icon-button"><Eye /></button><button className="icon-button"><FolderOpen /></button><button className="icon-button"><MoreVertical /></button></td></tr>)}</tbody></table></div><div className="pagination">Показано {filtered.length} із {reports.length}</div></section><aside className="panel report-details"><button className="close"><X /></button><h2>{filtered[0]?.name ?? "Рапортів не знайдено"}</h2><p><span className="word-icon">W</span> DOCX</p><div className="actions-line"><button className="button primary"><Eye />Відкрити</button><button className="button"><FolderOpen />Відкрити папку</button></div></aside></div></PageFrame>;
}
