import type { ReactNode } from "react";
import { Plus } from "lucide-react";
import { useEffect, useState } from "react";
import { personnelService } from "../services/personnelService";
import type { CustomFieldDefinition } from "../types/domain";
import { useNotifications } from "./NotificationProvider";

export function PageTitle({ title, subtitle, actions }: { title: string; subtitle: string; actions?: ReactNode }) {
  const [showField, setShowField] = useState(false);
  const [field, setField] = useState<CustomFieldDefinition>({ fieldKey: "", displayName: "", description: "", initialValue: "" });
  const [editingFieldKey, setEditingFieldKey] = useState<string | null>(null);
  const [fields, setFields] = useState<CustomFieldDefinition[]>([]);
  const { notify } = useNotifications();
  useEffect(() => { if (title === "Особовий склад") void personnelService.listCustomFields().then(setFields).catch(() => undefined); }, [title]);
  const createField = async () => { try { const saved = editingFieldKey ? await personnelService.updateCustomField({ ...field, fieldKey: editingFieldKey }) : await personnelService.createCustomField(field); setFields((current) => current.some((item) => item.fieldKey === saved.fieldKey) ? current.map((item) => item.fieldKey === saved.fieldKey ? saved : item) : [...current, saved]); setShowField(false); setEditingFieldKey(null); setField({ fieldKey: "", displayName: "", description: "", initialValue: "" }); window.dispatchEvent(new Event("personnel-refresh")); notify("Поле БД збережено.", "success"); } catch (error) { notify(error instanceof Error ? error.message : "Не вдалося зберегти поле БД.", "error"); } };
  const removeField = async (fieldKey: string) => { try { await personnelService.deleteCustomField(fieldKey); setFields((current) => current.filter((item) => item.fieldKey !== fieldKey)); window.dispatchEvent(new Event("personnel-refresh")); notify("Поле БД видалено.", "success"); } catch (error) { notify(error instanceof Error ? error.message : "Не вдалося видалити поле БД.", "error"); } };
  return <><div className="page-title"><div><h1>{title}</h1><p>{subtitle}</p></div>{actions && <div className="header-actions">{title === "Особовий склад" && <button className="button" onClick={() => { setEditingFieldKey(null); setField({ fieldKey: "", displayName: "", description: "", initialValue: "" }); setShowField(true); }}><Plus />Додати поле БД</button>}{actions}</div>}</div>{showField && <div className="modal-backdrop"><section className="modal"><h2>{editingFieldKey ? "Редагування поля БД" : "Нове поле БД"}</h2><p>Поле буде доступним у конструкторі змінних і синхронізується з custom_variables.json.</p><label>Ключ поля<input disabled={Boolean(editingFieldKey)} value={field.fieldKey} onChange={(event) => setField({ ...field, fieldKey: event.target.value })} placeholder="unit_name" /></label><label>Українська назва<input value={field.displayName} onChange={(event) => setField({ ...field, displayName: event.target.value })} /></label><label>Опис<textarea value={field.description} onChange={(event) => setField({ ...field, description: event.target.value })} /></label><label>Початкове значення<input value={field.initialValue} onChange={(event) => setField({ ...field, initialValue: event.target.value })} /></label><div className="modal-actions"><button className="button" onClick={() => { setShowField(false); setEditingFieldKey(null); }}>Скасувати</button><button className="button primary" onClick={() => void createField()}>Зберегти поле</button></div>{fields.length > 0 && <div className="custom-field-list"><h3>Створені поля</h3>{fields.map((item) => <div key={item.fieldKey}><span>{item.displayName} <code>{item.fieldKey}</code></span><button className="button" onClick={() => { setEditingFieldKey(item.fieldKey); setField(item); }}><span>Редагувати</span></button><button className="button danger" onClick={() => void removeField(item.fieldKey)}>Видалити</button></div>)}</div>}</section></div>}</>;
}
