import { CalendarDays, CheckCircle2, ChevronDown, CircleAlert, Download, Filter, Pencil, RefreshCw, Trash2, Upload, UserPlus, Users, X } from "lucide-react";
import type { Person } from "../../shared/types/domain";
import { CheckBox } from "../../shared/ui/CheckBox";
import { PageFrame } from "../../shared/ui/PageFrame";
import { PageTitle } from "../../shared/ui/PageTitle";
import { SearchInput } from "../../shared/ui/SearchInput";
import { Stat } from "../../shared/ui/Stat";

export function PersonnelPage({ people, detailsOpen, onDetails }: { people: Person[]; detailsOpen: boolean; onDetails: () => void }) {
  const tools = <><div className="table-tools main-tools"><SearchInput placeholder="Пошук за ПІБ, позивним або табельним номером…" /><button className="button"><Filter />Додаткові фільтри <ChevronDown /></button></div><div className="filter-bar"><button>Усі <b>128</b></button><button>З незаповненими полями <b className="yellow">17</b></button>{["Підрозділ", "Посада", "Звання"].map((label) => <span key={label}>{label}<button className="select">Усі <ChevronDown /></button></span>)}<button className="reset" aria-label="Скинути фільтри" title="Скинути фільтри"><RefreshCw />Скинути фільтри</button></div></>;
  const footer = <div className="statbar"><Stat icon={Users} label="Усього військовослужбовців" value="128" /><Stat icon={CheckCircle2} label="Повні дані" value="111" tone="green" /><Stat icon={CircleAlert} label="Неповні дані" value="17" tone="yellow" /><Stat icon={CalendarDays} label="Оновлено сьогодні" value="5" /><Stat icon={Upload} label="Імпортовано записів" value="0" /><Stat icon={Download} label="Експортовано записів" value="12" /></div>;
  return <PageFrame header={<PageTitle title="Особовий склад" subtitle="Облік та керування даними військовослужбовців" actions={<><button className="button primary"><UserPlus />Додати військовослужбовця <ChevronDown /></button><button className="button"><Upload />Імпорт</button><button className="button"><Download />Експорт</button></>} />} tools={tools} footer={footer} className="personnel-page"><div className={`people-layout ${detailsOpen ? "with-details" : ""}`}><section className="panel data-table"><div className="data-table__scroll"><table><thead><tr><th><CheckBox /></th><th>ПІБ</th><th>Позивний</th><th>Звання</th><th>Посада</th><th>Підрозділ</th><th>Статус даних</th><th>Дії</th></tr></thead><tbody>{people.map((person, index) => { const incomplete = [3, 5, 9].includes(index); return <tr className={incomplete ? "incomplete" : ""} key={person.id}><td><CheckBox /></td><td>{person.fullName}</td><td>{["Хижак", "Барс", "Скіф", "Фенікс", "Тихий", "Малюк", "Шева", "Джміль", "Рись", "Док"][index]}</td><td>{person.rank}</td><td>{person.position}</td><td>{person.unit}</td><td><span className={incomplete ? "status-incomplete" : "status-complete"}>{incomplete ? <CircleAlert /> : <CheckCircle2 />}{incomplete ? "Неповні дані" : "Повні дані"}</span></td><td><button className="icon-button" onClick={onDetails}><Pencil /></button><button className="icon-button danger"><Trash2 /></button></td></tr>; })}</tbody></table></div><div className="pagination">Показано 1–10 із 128 <span>‹ <b>1</b> 2 3 … 13 › <button className="button">10 / сторінка <ChevronDown /></button></span></div></section>{detailsOpen && <aside className="panel person-details"><button className="close" onClick={onDetails}><X /></button><h2>Деталі військовослужбовця</h2><div className="identity"><div className="avatar">ІІ</div><div><b>Іваненко Іван Іванович</b><p>Позивний: Хижак</p><span className="status-complete"><CheckCircle2 />Повні дані</span></div></div><div className="tabs"><button className="tab-active">Основні дані</button><button>Додаткові дані</button></div>{[["ПІБ *", "Іваненко Іван Іванович"], ["Позивний", "Хижак"], ["Звання", "Солдат"], ["Посада", "Стрілець"], ["Підрозділ", "1 взвод"], ["Дата народження", "14.05.1998"]].map(([label, value]) => <label className="field" key={label}>{label}<input value={value} readOnly /></label>)}</aside>}</div></PageFrame>;
}
