import { Database, Folder, FolderOpen, Pencil, Users } from "lucide-react";
import { PageFrame } from "../../shared/ui/PageFrame";
import { PageTitle } from "../../shared/ui/PageTitle";
import { SignerForm } from "./components/SignerForm";

type Tab = "paths" | "signers";
export function SettingsPage({ active, onChange }: { active: Tab; onChange: (tab: Tab) => void }) {
  const paths = [["Папка шаблонів", "Документи шаблонів рапортів (.docx)", "C:\\Генератор рапортів\\Шаблони", Folder], ["Папка згенерованих рапортів", "Тут зберігаються створені рапорти", "C:\\Генератор рапортів\\Згенеровані рапорти", Folder], ["Папка підписів", "PNG файли підписів", "C:\\Генератор рапортів\\Підписи", Pencil], ["Файл бази даних (SQLite)", "Локальна база даних програми", "C:\\Генератор рапортів\\База даних\\особовий_склад.db", Database]] as const;
  const tools = <div className="settings-tabs"><button className={active === "paths" ? "tab-active" : ""} onClick={() => onChange("paths")}><Folder />Шляхи</button><button className={active === "signers" ? "tab-active" : ""} onClick={() => onChange("signers")}><Users />Підписанти</button></div>;
  return <PageFrame header={<PageTitle title="Налаштування" subtitle="Керування шляхами та даними програми" />} tools={tools} className="settings-page">{active === "paths" ? <section className="panel settings-panel"><h2>Шляхи до файлів та папок</h2><p>Вкажіть розташування основних файлів і папок програми.</p>{paths.map(([title, description, path, Icon]) => <article className="path-row" key={title}><Icon className="green" /><div><b>{title}</b><p>{description}</p><input value={path} readOnly /></div><div><button className="button"><FolderOpen />Відкрити</button><button className="button"><Pencil />Змінити</button></div></article>)}<div className="settings-tip">ⓘ Після зміни шляхів перезапуск програми не потрібен.<br />Нові налаштування застосовуються автоматично.</div></section> : <section className="panel settings-panel signers"><h2>Дані підписантів</h2><p>Ці дані використовуються в усіх шаблонах рапортів.</p><SignerForm number={1} role="Основний підписант" name="Іваненко Іван Іванович" rank="майор" position="Заступник командира з ППП" mark="✍" /><SignerForm number={2} role="Командир" name="Петренко Петро Петрович" rank="капітан" position="Командир" mark="♜" /><SignerForm number={3} role="Начальник штабу" name="Сидоренко Сергій Сергійович" rank="капітан" position="Начальник штабу" mark="♜" /></section>}</PageFrame>;
}
