import { Archive, Download, FileSpreadsheet, FolderOpen, Upload, Users } from "lucide-react";
import { useEffect, useState } from "react";
import { open, save } from "@tauri-apps/plugin-dialog";
import { PageFrame } from "../../shared/ui/PageFrame";
import { PageTitle } from "../../shared/ui/PageTitle";
import { Modal } from "../../shared/ui/Modal";
import { useNotifications } from "../../shared/ui/NotificationProvider";
import { personnelService } from "../../shared/services/personnelService";
import { SignerForm } from "./components/SignerForm";
import { useAppSettings } from "./hooks/useAppSettings";
import { settingsService } from "./services/settingsService";
import type { SignerSettings } from "../../shared/types/domain";

export function SettingsPage() {
  const { settings, errorMessage, isSaving, updateSigner } = useAppSettings();
  const { notify } = useNotifications();
  const [exportOpen, setExportOpen] = useState(false);
  const [excelOpen, setExcelOpen] = useState(false);
  const [options, setOptions] = useState({ database: true, settings: true, customVariables: true, templates: true, reports: false });
  useEffect(() => { if (errorMessage) notify(errorMessage, "error"); }, [errorMessage, notify]);
  const createBackup = async () => { try { await settingsService.createDatabaseBackup(); notify("Резервну копію бази даних створено.", "success"); } catch { notify("Не вдалося створити резервну копію бази даних.", "error"); } };
  const importExcel = async (mode: "append" | "replace") => { try { const path = await open({ title: "Імпорт Excel-бази даних", filters: [{ name: "Таблиця Excel", extensions: ["xlsx"] }] }); if (!path || Array.isArray(path)) return; await personnelService.importExcel(path, mode); setExcelOpen(false); notify("Excel-базу імпортовано.", "success"); window.location.reload(); } catch { notify("Не вдалося імпортувати Excel-базу даних.", "error"); } };
  const exportExcel = async () => { try { const path = await save({ title: "Експорт Excel-бази даних", defaultPath: "Excel-база.xlsx", filters: [{ name: "Таблиця Excel", extensions: ["xlsx"] }] }); if (!path) return; await personnelService.exportExcel(path.endsWith(".xlsx") ? path : `${path}.xlsx`); notify("Excel-базу експортовано.", "success"); } catch { notify("Не вдалося експортувати Excel-базу даних.", "error"); } };
  const importArchive = async () => { try { const path = await open({ title: "Імпорт архіву даних", filters: [{ name: "Архів перенесення", extensions: ["zip"] }] }); if (!path || Array.isArray(path)) return; await settingsService.importApplicationData(path); notify("Дані відновлено.", "success"); window.location.reload(); } catch { notify("Не вдалося імпортувати архів даних.", "error"); } };
  const exportArchive = async () => { try { const path = await save({ title: "Експорт усіх даних", defaultPath: "RaportGen-перенесення.zip", filters: [{ name: "Архів перенесення", extensions: ["zip"] }] }); if (!path) return; await settingsService.exportApplicationData(path.endsWith(".zip") ? path : `${path}.zip`, options); setExportOpen(false); notify("Архів даних створено.", "success"); } catch { notify("Не вдалося створити архів даних.", "error"); } };
  const signer = (number: number, role: "main" | "commander" | "chief" | "deputyPpp" | "deputyArmament" | "deputyRear" | "fuelChief", title: string, value: SignerSettings) => <SignerForm number={number} role={role} title={title} value={value} isSaving={isSaving} onSave={updateSigner} />;
  return <PageFrame header={<PageTitle title="Налаштування" subtitle="Підписанти, Excel-база та перенесення даних" />} className="settings-page"><section className="settings-content"><section className="panel settings-panel signers"><header className="settings-section-title"><Users /><div><h2>Підписанти</h2><p>Дані ролей доступні у шаблонах.</p></div></header>{settings ? <>{signer(1,"main","Основний підписант",settings.mainSigner)}{signer(2,"commander","Командир",settings.commander)}{signer(3,"chief","Начальник штабу",settings.chief,)}{signer(4,"deputyPpp","Заступник командира з ППП",settings.deputyPpp)}{signer(5,"deputyArmament","Заступник командира з озброєння",settings.deputyArmament)}{signer(6,"deputyRear","Заступник командира з тилу",settings.deputyRear)}{signer(7,"fuelChief","Начальник ПММ",settings.fuelChief)}</> : <p>Завантаження налаштувань…</p>}</section><aside className="panel settings-actions"><button className="button" onClick={() => void settingsService.openApplicationDirectory()}><FolderOpen />Відкрити директорію</button><button className="button" onClick={() => void settingsService.createDatabaseBackup()}><Archive />Резервна копія БД</button><button className="button" onClick={() => setExcelOpen(true)}><FileSpreadsheet />Імпорт Excel-бази</button><button className="button" onClick={() => void exportExcel()}><FileSpreadsheet />Експорт Excel-бази</button><button className="button" onClick={() => setExportOpen(true)}><Download />Експортувати всі дані</button><button className="button" onClick={() => void importArchive()}><Upload />Імпортувати архів даних</button></aside></section>{excelOpen && <Modal title="Імпорт Excel-бази даних" onClose={() => setExcelOpen(false)}><p>Оберіть спосіб імпорту записів.</p><button className="personnel-import-option" onClick={() => void importExcel("append")}><b>Доповнити БД</b><span>Додати записи до наявних.</span></button><button className="personnel-import-option personnel-import-option--danger" onClick={() => void importExcel("replace")}><b>Замінити БД</b><span>Повністю замінити записи.</span></button></Modal>}{exportOpen && <Modal title="Експорт усіх даних" onClose={() => setExportOpen(false)}><p>Оберіть складові архіву.</p>{Object.entries({ database: "База даних", settings: "Налаштування", customVariables: "Кастомні поля", templates: "Шаблони", reports: "Згенеровані рапорти" }).map(([key, label]) => <label key={key}><input type="checkbox" checked={options[key as keyof typeof options]} onChange={() => setOptions((current) => ({ ...current, [key]: !current[key as keyof typeof current] }))} /> {label}</label>)}<footer className="modal-actions"><button className="button" onClick={() => setExportOpen(false)}>Скасувати</button><button className="button primary" onClick={() => void exportArchive()}>Створити архів</button></footer></Modal>}</PageFrame>;
}
