import { invoke } from "@tauri-apps/api/core";
import type { Crew, CrewDraft, Equipment, EquipmentCategory, EquipmentDraft, FlightPlanRequest, Incident, IncidentDraft, Position, PositionDraft, StaffRecommendation, StaffingRecord, VacancyRecommendation } from "../types";

export const operationsService = {
  listCrews: () => invoke<Crew[]>("list_crews"),
  createCrew: (draft: CrewDraft) => invoke<void>("create_crew", { draft }),
  updateCrew: (crewId: number, draft: CrewDraft) => invoke<void>("update_crew", { crewId, draft }),
  deleteCrew: (crewId: number) => invoke<void>("delete_crew", { crewId }),
  listTemporaryPersonnel: () => invoke<import("../types").TemporaryPerson[]>("list_temporary_personnel"),
  saveTemporaryPersonnel: (person: import("../types").TemporaryPerson) => invoke<void>("save_temporary_personnel", { person }),
  deleteTemporaryPersonnel: (personId: number) => invoke<void>("delete_temporary_personnel", { personId }),
  listStaffingRecords: () => invoke<StaffingRecord[]>("list_staffing_records"),
  syncFlightPlanLocations: (crewIds: number[]) => invoke<void>("sync_flight_plan_locations", { crewIds }),
  updateStaffingPersonnel: (payload: { personnelId: number; position: string; actingPosition: string; currentLocation: string; functionalDuties: string; notes: string }) => invoke<void>("update_staffing_personnel", payload),
  transferStaffingChain: (assignments: import("../staffing-slots").SlotTransfer[], actingChanges: import("../staffing-slots").ActingChange[] = []) => invoke<void>("transfer_staffing_chain", { assignments, actingChanges }),
  createStaffRecommendation: (payload: { personnelId: number; positionName: string; issuedAt: string; notes: string }) => invoke<void>("create_staff_recommendation", payload),
  listStaffRecommendations: () => invoke<StaffRecommendation[]>("list_staff_recommendations"),
  createVacancyRecommendation: (payload: { slotId?: string; positionName: string; fullName: string; phone: string; rank: string; birthDate: string; issuedAt: string; notes: string }) => invoke<void>("create_vacancy_recommendation", payload),
  listVacancyRecommendations: () => invoke<VacancyRecommendation[]>("list_vacancy_recommendations"),
  updateBcsCrewStrength: (crewId: number, value: number) => invoke<void>("update_bcs_crew_strength", { crewId, value }),
  exportBcs: (path: string, unitName: string, date: string, rows: import("../bcs-model").BcsExportRow[]) => invoke<void>("export_bcs_excel", { path, unitName, date, rows }),
  exportFlightPlan: (path: string, request: FlightPlanRequest) => invoke<void>("export_flight_plan_excel", { path, request }),
  listPositions: () => invoke<Position[]>("list_positions"),
  createPosition: (draft: PositionDraft) => invoke<void>("create_position", { draft }),
  updatePosition: (positionId: number, draft: PositionDraft) => invoke<void>("update_position", { positionId, draft }),
  deletePosition: (positionId: number) => invoke<void>("delete_position", { positionId }),
  listEquipment: (category: EquipmentCategory) => invoke<Equipment[]>("list_equipment", { category }),
  createEquipment: (draft: EquipmentDraft) => invoke<void>("create_equipment", { draft }),
  updateEquipment: (equipmentId: number, draft: EquipmentDraft) => invoke<void>("update_equipment", { equipmentId, draft }),
  assignEquipment: (equipmentId: number, crewId: number | null) => invoke<void>("assign_equipment", { equipmentId, crewId }),
  deleteEquipment: (equipmentId: number) => invoke<void>("delete_equipment", { equipmentId }),
  listIncidents: () => invoke<Incident[]>("list_incidents"),
  createIncident: (draft: IncidentDraft) => invoke<void>("create_incident", { draft }),
};
