import { CheckCircle2, FileCheck2, FileText, Filter, Folder } from "lucide-react";
import type { Person, Template } from "../../shared/types/domain";
import { templates } from "../../shared/constants/mock-data";
import { CheckBox } from "../../shared/ui/CheckBox";
import { PageFrame } from "../../shared/ui/PageFrame";
import { SearchInput } from "../../shared/ui/SearchInput";

type Props = { template: Template | null; people: Person[]; selected: number[]; onToggle: (id: number) => void; onAll: () => void; onChoose: (template: Template) => void };
export function ReportGenerationPage({ template, people, selected, onToggle, onAll, onChoose }: Props) { return <PageFrame className="generation-page"><div className="generation-layout"><section className="panel template-picker"><div className="empty-template"><FileText size={75} /><h2>{template?.name ?? "Виберіть шаблон рапорту"}</h2><p>{template?.description ?? "Оберіть шаблон зі списку, щоб перейти до вибору військовослужбовців"}</p></div><div className="panel-caption"><b>Доступні шаблони</b><SearchInput placeholder="Пошук шаблонів…" /></div><div className="template-grid template-picker__scroll">{templates.map((item) => <button onClick={() => onChoose(item)} key={item.name} className={`template-card ${template?.name === item.name ? "template-selected" : ""}`}><FileText /><div><b>{item.name}</b><p>{item.description}</p><small>Оновлено: {item.changed} · DOCX</small></div>{template?.name === item.name && <CheckCircle2 className="green" />}</button>)}</div><button className="file-open"><Folder />Відкрити шаблон з файлу…<small>Підтримувані формати: .docx</small></button></section><section className="selection-column"><div className="panel people-select"><h2>Вибір військовослужбовців <span className="info">i</span></h2><div className="tip">ⓘ Виберіть одного або кількох військовослужбовців.<br />Якщо обрано кількох — рапорт буде створено для кожного.</div><div className="table-tools"><SearchInput placeholder="Пошук за ПІБ, ІПН, посадою…" /><button className="button"><Filter size={17} />Фільтри</button></div><div className="people-select__scroll"><table><thead><tr><th><CheckBox checked={selected.length === people.length} onChange={onAll} /></th><th>Звання</th><th>ПІБ</th><th>Посада</th><th>Військовий квиток</th></tr></thead><tbody>{people.map((person) => <tr key={person.id}><td><CheckBox checked={selected.includes(person.id)} onChange={() => onToggle(person.id)} /></td><td>{person.rank}</td><td>{person.fullName}</td><td>{person.position}</td><td>{person.militaryId}</td></tr>)}</tbody></table></div><div className="selection-footer">Вибрано: <b className="green">{selected.length}</b><span /><button className="button muted">Очистити вибір</button><button className="button" onClick={onAll}>Вибрати всіх</button></div></div><button className="generate-button" disabled={!template || !selected.length}><FileCheck2 />Згенерувати рапорт</button><p className="generate-hint">{!template || !selected.length ? "Спочатку виберіть шаблон та військовослужбовців" : `Буде створено рапортів: ${selected.length}`}</p></section></div></PageFrame>; }
