PRAGMA foreign_keys = ON;
BEGIN IMMEDIATE;

INSERT INTO flight_plan_snapshots(plan_date, revision, source, snapshot_json)
SELECT '2026-09-13', 1, 'saved', '{"unitName":"РБАК","entries":[{"crewId":1,"actualMemberIds":[12,13,14,15],"actualCommanderId":12,"actualVehicleId":1,"weather":{"temperature":"18","windFrom":"2","windTo":"4","gustFrom":"4","gustTo":"7","cloudiness":"мінлива","cloudHeight":"900","precipitation":"без опадів"},"routePoints":["НОВОСЕЛІВКА","район виконання завдання"],"altitudeFrom":"800","altitudeTo":"1100","areaPoints":["ПІВНІЧНИЙ РАЙОН"],"task":"Повітряна розвідка","startTime":"18:01","endTime":"23:59","uavSelections":[{"equipmentId":13,"dayQuantity":1,"nightQuantity":1}],"payloadSelection":null},{"crewId":2,"actualMemberIds":[16,17,18,19],"actualCommanderId":16,"actualVehicleId":2,"weather":{"temperature":"18","windFrom":"2","windTo":"4","gustFrom":"4","gustTo":"7","cloudiness":"мінлива","cloudHeight":"900","precipitation":"без опадів"},"routePoints":["НОВОСЕЛІВКА","східний маршрут"],"altitudeFrom":"900","altitudeTo":"1200","areaPoints":["СХІДНИЙ РАЙОН"],"task":"Повітряна розвідка","startTime":"18:01","endTime":"23:59","uavSelections":[{"equipmentId":14,"dayQuantity":1,"nightQuantity":1}],"payloadSelection":null}]}'
WHERE NOT EXISTS (SELECT 1 FROM flight_plan_snapshots WHERE plan_date='2026-09-13');

INSERT INTO flight_plan_snapshots(plan_date, revision, source, snapshot_json)
SELECT '2026-09-14', 1, 'saved', '{"unitName":"РБАК","entries":[{"crewId":1,"actualMemberIds":[12,13,14,15],"actualCommanderId":12,"actualVehicleId":1,"weather":{"temperature":"21","windFrom":"3","windTo":"5","gustFrom":"5","gustTo":"8","cloudiness":"малохмарно","cloudHeight":"1200","precipitation":"без опадів"},"routePoints":["НОВОСЕЛІВКА","район виконання завдання"],"altitudeFrom":"800","altitudeTo":"1100","areaPoints":["ПІВНІЧНИЙ РАЙОН"],"task":"Повітряна розвідка","startTime":"00:00","endTime":"18:00","uavSelections":[{"equipmentId":13,"dayQuantity":2,"nightQuantity":0}],"payloadSelection":null},{"crewId":2,"actualMemberIds":[16,17,18,19],"actualCommanderId":16,"actualVehicleId":2,"weather":{"temperature":"21","windFrom":"3","windTo":"5","gustFrom":"5","gustTo":"8","cloudiness":"малохмарно","cloudHeight":"1200","precipitation":"без опадів"},"routePoints":["НОВОСЕЛІВКА","східний маршрут"],"altitudeFrom":"900","altitudeTo":"1200","areaPoints":["СХІДНИЙ РАЙОН"],"task":"Повітряна розвідка","startTime":"00:00","endTime":"18:00","uavSelections":[{"equipmentId":14,"dayQuantity":2,"nightQuantity":0}],"payloadSelection":null},{"crewId":3,"actualMemberIds":[20,21,22,23],"actualCommanderId":20,"actualVehicleId":3,"weather":{"temperature":"21","windFrom":"3","windTo":"5","gustFrom":"5","gustTo":"8","cloudiness":"малохмарно","cloudHeight":"1200","precipitation":"без опадів"},"routePoints":["СТЕПОВЕ","південний маршрут"],"altitudeFrom":"1000","altitudeTo":"1400","areaPoints":["ПІВДЕННИЙ РАЙОН"],"task":"Повітряна розвідка","startTime":"06:00","endTime":"18:00","uavSelections":[{"equipmentId":15,"dayQuantity":2,"nightQuantity":0}],"payloadSelection":null}]}'
WHERE NOT EXISTS (SELECT 1 FROM flight_plan_snapshots WHERE plan_date='2026-09-14');

INSERT INTO flight_journal_entries(flight_date,sky_time,ground_time,crew_id,position_id,uav_id,crew_name_snapshot,position_name_snapshot,battle_order_snapshot,work_strip_snapshot,uav_name_snapshot,uav_serial_snapshot,uav_type_snapshot,mission,notes)
SELECT '2026-09-13','20:15','21:05',1,1,13,'СОКІЛ','БУРЕВІЙ','БРО-01','СМУГА ПІВНІЧ','MAVIC 3T','UAV-001','Коптер','Повітряна розвідка','Контроль північного маршруту' WHERE NOT EXISTS (SELECT 1 FROM flight_journal_entries WHERE flight_date='2026-09-13' AND sky_time='20:15' AND crew_id=1);
INSERT INTO flight_journal_entries(flight_date,sky_time,ground_time,crew_id,position_id,uav_id,crew_name_snapshot,position_name_snapshot,battle_order_snapshot,work_strip_snapshot,uav_name_snapshot,uav_serial_snapshot,uav_type_snapshot,mission,notes)
SELECT '2026-09-13','22:40','23:25',2,2,14,'БАРС','САПСАН','БРО-02','СМУГА ПІВНІЧ','SHARK','UAV-002','Літаковий розвідувальний','Повітряна розвідка','Уточнення обстановки' WHERE NOT EXISTS (SELECT 1 FROM flight_journal_entries WHERE flight_date='2026-09-13' AND sky_time='22:40' AND crew_id=2);
INSERT INTO flight_journal_entries(flight_date,sky_time,ground_time,crew_id,position_id,uav_id,crew_name_snapshot,position_name_snapshot,battle_order_snapshot,work_strip_snapshot,uav_name_snapshot,uav_serial_snapshot,uav_type_snapshot,mission,notes)
SELECT '2026-09-14','06:20','07:10',1,1,25,'СОКІЛ','БУРЕВІЙ','БРО-01','СМУГА ПІВНІЧ','MAVIC 3T','UAV-013','Коптер','Повітряна розвідка','Ранковий контроль' WHERE NOT EXISTS (SELECT 1 FROM flight_journal_entries WHERE flight_date='2026-09-14' AND sky_time='06:20' AND crew_id=1);
INSERT INTO flight_journal_entries(flight_date,sky_time,ground_time,crew_id,position_id,uav_id,crew_name_snapshot,position_name_snapshot,battle_order_snapshot,work_strip_snapshot,uav_name_snapshot,uav_serial_snapshot,uav_type_snapshot,mission,notes)
SELECT '2026-09-14','09:35','11:00',2,2,26,'БАРС','САПСАН','БРО-02','СМУГА ПІВНІЧ','SHARK','UAV-014','Літаковий розвідувальний','Повітряна розвідка','Планове завдання' WHERE NOT EXISTS (SELECT 1 FROM flight_journal_entries WHERE flight_date='2026-09-14' AND sky_time='09:35' AND crew_id=2);
INSERT INTO flight_journal_entries(flight_date,sky_time,ground_time,crew_id,position_id,uav_id,crew_name_snapshot,position_name_snapshot,battle_order_snapshot,work_strip_snapshot,uav_name_snapshot,uav_serial_snapshot,uav_type_snapshot,mission,notes)
SELECT '2026-09-14','12:10','13:20',3,3,15,'ГРІМ','ХИЖАК','БРО-03','СМУГА СХІД','LELEKA-100','UAV-003','Літаковий розвідувальний','Повітряна розвідка','Контроль району відповідальності' WHERE NOT EXISTS (SELECT 1 FROM flight_journal_entries WHERE flight_date='2026-09-14' AND sky_time='12:10' AND crew_id=3);
INSERT INTO flight_journal_entries(flight_date,sky_time,ground_time,crew_id,position_id,uav_id,crew_name_snapshot,position_name_snapshot,battle_order_snapshot,work_strip_snapshot,uav_name_snapshot,uav_serial_snapshot,uav_type_snapshot,mission,notes)
SELECT '2026-09-14','16:05','17:15',3,3,27,'ГРІМ','ХИЖАК','БРО-03','СМУГА СХІД','LELEKA-100','UAV-015','Літаковий розвідувальний','Повітряна розвідка','Заключний виліт за період' WHERE NOT EXISTS (SELECT 1 FROM flight_journal_entries WHERE flight_date='2026-09-14' AND sky_time='16:05' AND crew_id=3);

INSERT INTO summary_report_drafts(report_date,manual_json)
VALUES('2026-09-14','{"reportNumber":"2555/8580-в/дск","enemyLosses":{"personnel":"0","irreversible":"0","sanitary":"0","captured":"0","ovt":"0","ovtDestroyed":"0","ovtDamaged":"0","tanks":"0","tanksDestroyed":"0","tanksDamaged":"0","afv":"0","afvDestroyed":"0","afvDamaged":"0","artillery":"0","artilleryDestroyed":"0","artilleryDamaged":"0","mlrs":"0","mlrsDestroyed":"0","mlrsDamaged":"0","reb":"0","rebDestroyed":"0","rebDamaged":"0","vehicles":"0","vehiclesDestroyed":"0","vehiclesDamaged":"0","aircraft":"0","aircraftDestroyed":"0","aircraftDamaged":"0","uav":"0","uavDestroyed":"0","uavDamaged":"0","airDefence":"0","communications":"0"},"compositionOverride":false,"compositionChanges":"Без змін","completeness":{"personnel":"78%","weapons":"100%","equipment":"75%"},"rocketStrikes":"0","airStrikes":"0","va":"0","sha":"0","aa":"0","enemyAssault":false,"enemyAssaultText":"Не проводив.","shellings":[],"ownAssault":false,"ownAssaultText":"Не проводили.","commandDuties":[{"id":"seed-command-1","personnelId":1,"text":"з 18:01 год 13.09.2026 по 06:00 год 14.09.2026"},{"id":"seed-command-2","personnelId":2,"text":"з 06:00 год по 18:00 год 14.09.2026"}],"guardDuties":[{"id":"seed-guard-1","personnelId":3,"text":"з 18:01 год 13.09.2026 по 06:00 год 14.09.2026"},{"id":"seed-guard-2","personnelId":4,"text":"з 06:00 год по 18:00 год 14.09.2026"}],"manualEvents":[{"id":"seed-event-1","text":"09:00 год 14.09.2026 проведено перевірку готовності чергових сил і засобів."}],"autoEventEdits":{},"autoOverrides":{},"autoBaselines":{},"commissionsOverride":false,"commissions":"В поточному періоді не працювали.","fortificationOverride":false,"fortification":"Заходи з фортифікаційного обладнання не велись.","dzvinOverride":false,"dzvin":"Зміни не відбувалися.","nextTasks":[{"id":"seed-task-1","text":"Продовжити ведення повітряної розвідки у визначених смугах відповідальності."},{"id":"seed-task-2","text":"Підтримувати готовність екіпажів і засобів до виконання завдань."}],"personnelLosses":{"total":"0","irreversible":"0","combatIrreversible":"0","killed":"0","diedFromWounds":"0","other":"0","temporary":"0","combatTemporary":"0","wounded":"0","captured":"0","missing":"0","deserters":"0","szch":"0","sick":"0"},"equipmentLosses":{"total":"0","destroyed":"0","damaged":"0","lost":"0","tanks":"0","afv":"0","artillery":"0","airDefence":"0","vehicles":"0","reb":"0","communications":"0","uav":"0"},"equipmentLossesDetails":"Відсутні.","ammunitionExpenses":"-не застосовувалися.","problems":"Проблемних питань, що потребують вирішення на вищому рівні, немає.","otherIssues":[{"id":"seed-other-1","text":"-відсутні."}]}' )
ON CONFLICT(report_date) DO UPDATE SET manual_json=excluded.manual_json,updated_at=CURRENT_TIMESTAMP;

COMMIT;
