import { Fragment, type CSSProperties } from "react";
import schema from "../../shared/bcs-schema.json";
import { BCS_HEADERS, BCS_LOCATIONS, bcsCaps, bcsComposedNotes, bcsGroups, bcsManualNotes, bcsSummary, bcsFunctionalSummary, canonicalCrewStatus, crewWorkingStrength } from "./bcs-model";
import type { StaffingRecord } from "./types";

type BcsPatch = { currentLocation?: string; notes?: string; functionalDuties?: string };
export function BcsTable({ records, authorized, zoom, onSave, readOnly = false, notesReadOnly = readOnly }: { records: StaffingRecord[]; authorized: number; zoom: number; onSave: (person: StaffingRecord, patch: BcsPatch) => Promise<void>; readOnly?: boolean; notesReadOnly?: boolean }) {
  const groups = bcsGroups(records);
  const personnelRecords = records.filter((person)=>!person.isCrewPlaceholder);
  const scaleStyle = { "--bcs-zoom": zoom / 100 } as CSSProperties;
  const displayWidths = schema.widths.map((width, index) => {
    if (index === 7) return 26;
    if (index === 9) return 34;
    if (index === 11) return 28;
    if (index === 12) return 55;
    if (index === 13) return 55;
    return width;
  });
  return <div className="bcs-scale" style={scaleStyle}><section className="panel bcs-reference"><div className="bcs-reference__scroll"><table><colgroup>{displayWidths.map((width, index) => <col key={index} style={{ width: `${width * 5}px` }} />)}</colgroup><thead><tr>{BCS_HEADERS.map((title,index) => <th title={title.replace("\n"," ")} className={index===7?"bcs-reference__crew-status":index===9?"bcs-reference__uav-type":undefined} key={title}>{title.replace("\n"," ")}</th>)}</tr></thead><tbody>
    {groups.map(({ key, people, section, colorKey }) => <Fragment key={key}>{people.map((person, index) => <tr key={person.personnelId} className={`bcs-reference__${colorKey} ${index === 0 ? "bcs-reference__group-start" : ""}`}>
      {index === 0 && <><td rowSpan={people.length}>{section}</td><td rowSpan={people.length}>{section === "Екіпаж" ? bcsCaps(person.crewPositionName) : ""}</td><td rowSpan={people.length}>{section === "Екіпаж" ? person.battleOrder : ""}</td><td rowSpan={people.length}>{section === "Екіпаж" ? person.sector : ""}</td><td rowSpan={people.length}>{section === "Екіпаж" ? bcsCaps(person.crewName) : ""}</td><td rowSpan={people.length}>{section === "Екіпаж" ? crewWorkingStrength(records,person.crewId) : ""}</td><td rowSpan={people.length}>{section === "Екіпаж" ? person.actualStrength : people.length}</td><td className="bcs-reference__crew-status" title={canonicalCrewStatus(person.crewStatus)} rowSpan={people.length}>{section === "Екіпаж" ? canonicalCrewStatus(person.crewStatus) : ""}</td><td rowSpan={people.length}>{section === "Екіпаж" ? bcsCaps(person.uavName) : ""}</td><td className="bcs-reference__uav-type" title={person.uavType} rowSpan={people.length}>{section === "Екіпаж" ? person.uavType : ""}</td></>}
      {person.isCrewPlaceholder ? <td colSpan={6} className="bcs-reference__empty-crew">Офіційний склад екіпажу не визначено</td> : <><td className="bcs-reference__staff-position" title={person.position}>{person.position}</td><td title={person.rank}>{person.rank}</td><td title={person.fullName}>{person.fullName}</td><td><textarea wrap="off" aria-label={`Функціональні обов’язки: ${person.fullName}`} key={`${person.personnelId}-${person.functionalDuties}`} defaultValue={person.functionalDuties} readOnly={readOnly} onBlur={(event) => { if (!readOnly && event.target.value !== person.functionalDuties) void onSave(person, { functionalDuties: event.target.value }); }} /></td><td><input aria-label={`Де знаходиться: ${person.fullName}`} value={person.currentLocation || "Не вказано"} readOnly title="Місце перебування змінюється у «Контролі особового складу» або автоматичним робочим процесом" /></td><td className="bcs-reference__notes"><textarea wrap="off" aria-label={`Примітка: ${person.fullName}`} key={`${person.personnelId}-${person.notes}-${person.actualCrewId}`} defaultValue={bcsComposedNotes(person)} readOnly={notesReadOnly} onBlur={(event) => { if (notesReadOnly) return; const notes = bcsManualNotes({ ...person, notes: event.target.value }); if (notes !== bcsManualNotes(person)) void onSave(person, { notes }); }} /></td></>}
    </tr>)}</Fragment>)}
  </tbody></table></div></section><section className="bcs-reference__summaries"><table className="bcs-summary bcs-summary--unit"><caption>БЧС підрозділу</caption><tbody>{bcsSummary(records, authorized).map(([label, count]) => <tr key={label}><th>{label}</th><td>{count}</td></tr>)}</tbody></table><table className="bcs-summary bcs-summary--functional"><caption>БЧС по функціоналу</caption><tbody>{bcsFunctionalSummary(records).map(([label, count]) => <tr key={label}><th>{label}</th><td>{count}</td></tr>)}</tbody></table><table className="bcs-summary bcs-summary--locations"><caption>Де знаходиться</caption><tbody>{BCS_LOCATIONS.map((location) => <tr key={location}><th>{location}</th><td>{personnelRecords.filter((person) => person.currentLocation === location).length}</td></tr>)}<tr><th>Не вказано / інше</th><td>{personnelRecords.filter((person) => !BCS_LOCATIONS.includes(person.currentLocation)).length}</td></tr><tr><th>Загалом</th><td>{personnelRecords.length}</td></tr></tbody></table></section></div>;
}
