import { AlertTriangle, ChevronDown, MapPin, Plane, Route, Users } from "lucide-react";
import { useState } from "react";
import { Select } from "../../shared/ui/Select";
import type { Vehicle } from "../vehicles/types";
import { FLIGHT_TASKS } from "./flight-plan-model";
import { PointTagsInput } from "./PointTagsInput";
import type { Crew, Equipment, FlightPlanEntry, FlightPlanWeather } from "./types";

const weatherFields: Array<[keyof FlightPlanWeather,string]> = [["temperature","Температура, °С"],["windFrom","Вітер від, м/с"],["windTo","Вітер до, м/с"],["gustFrom","Пориви від, м/с"],["gustTo","Пориви до, м/с"],["cloudiness","Хмарність, %"],["cloudHeight","Висота хмар, м"],["precipitation","Вірогідність опадів, %"]];

export function FlightPlanParametersModal({ crews, vehicles, uavs, selected, entries, missingCallsignCount, onToggle, onPatch }: {
  crews:Crew[]; vehicles:Vehicle[]; uavs:Equipment[]; selected:number[]; entries:Record<number,FlightPlanEntry>; missingCallsignCount:number;
  onToggle:(crewId:number)=>void; onPatch:(crewId:number,patch:Partial<FlightPlanEntry>)=>void;
}) {
  const [expanded, setExpanded] = useState<Set<number>>(() => new Set());
  const toggleExpanded = (crewId:number) => setExpanded((current) => { const next=new Set(current); if(next.has(crewId))next.delete(crewId);else next.add(crewId); return next; });
  return <section className="panel flight-plan-parameters-panel"><div className="flight-plan-parameters">
      {missingCallsignCount>0&&<div className="flight-plan-modal-warning"><AlertTriangle/><span>У складі екіпажів немає позивних у {missingCallsignCount} людей. Для вибраних екіпажів експорт буде недоступний, доки позивні не заповнені.</span></div>}
      <section className="flight-plan-parameters__crews" aria-label={`Працюючі екіпажі: вибрано ${selected.length} з ${crews.length}`}>
        {crews.map((crew)=>{const checked=selected.includes(crew.id);const open=expanded.has(crew.id);const entry=entries[crew.id];if(!entry)return null;const crewVehicles=vehicles.filter((item)=>item.crewId===crew.id);const crewUavs=uavs.filter((item)=>item.crewId===crew.id);return <article className={`flight-plan-editor ${checked?"is-selected":""}`} key={crew.id}>
          <div className="flight-plan-editor__header"><label className="flight-plan-editor__select"><input type="checkbox" checked={checked} onChange={()=>onToggle(crew.id)}/><span><b>{crew.name}</b><small>{crew.positionName||"Позицію не визначено"}</small></span></label><div className="flight-plan-editor__facts"><span><MapPin/>{crew.battleOrder||"БРО не вказано"}</span><span><Plane/>{crew.uavName||"БпАК не вказано"}</span><span><Users/>{crew.actualMembers.length} фактично</span><em>{crew.status}</em></div><button type="button" className={`flight-plan-editor__expand ${open?"is-open":""}`} aria-label={`${open?"Згорнути":"Розгорнути"} ${crew.name}`} onClick={()=>toggleExpanded(crew.id)}><ChevronDown/></button></div>
          {open&&<div className="flight-plan-editor__fields">
            <fieldset><legend>БпЛА у плані польотів</legend><div className="flight-uav-selector">{crewUavs.map((uav)=>{const current=entry.uavSelections.find((item)=>item.equipmentId===uav.id);const patchQuantity=(key:"dayQuantity"|"nightQuantity",raw:number)=>{if(!current)return;const other=key==="dayQuantity"?current.nightQuantity:current.dayQuantity;const value=Math.max(0,Math.min(Number.isFinite(raw)?raw:0,uav.totalQuantity-other));onPatch(crew.id,{uavSelections:entry.uavSelections.map((item)=>item.equipmentId===uav.id?{...item,[key]:value}:item)});};return <article className={current?"selected":""} key={uav.id}><label><input type="checkbox" checked={!!current} onChange={()=>onPatch(crew.id,{uavSelections:current?entry.uavSelections.filter((item)=>item.equipmentId!==uav.id):[...entry.uavSelections,{equipmentId:uav.id,dayQuantity:uav.dayQuantity,nightQuantity:uav.nightQuantity}]})}/><span><b>{uav.name}</b><small>{uav.inventoryNumber||"Без номера"} · усього {uav.totalQuantity}</small></span></label>{current&&<div><label className="form-field"><span>Денні</span><input type="number" min="0" max={uav.totalQuantity-current.nightQuantity} value={current.dayQuantity} onChange={(event)=>patchQuantity("dayQuantity",Number(event.target.value))}/></label><label className="form-field"><span>Нічні</span><input type="number" min="0" max={uav.totalQuantity-current.dayQuantity} value={current.nightQuantity} onChange={(event)=>patchQuantity("nightQuantity",Number(event.target.value))}/></label></div>}</article>})}{!crewUavs.length&&<p>За екіпажем не закріплено жодного БпЛА.</p>}</div></fieldset>
            <fieldset><legend>Погода цього екіпажу</legend><div className="flight-weather__grid">{weatherFields.map(([key,label])=><label className="form-field" key={key}><span>{label}</span><input type="number" value={entry.weather[key]} onChange={(event)=>onPatch(crew.id,{weather:{...entry.weather,[key]:event.target.value}})}/></label>)}</div></fieldset>
            <div className="flight-plan-editor__route"><PointTagsInput label="Маршрут — населені пункти" value={entry.routePoints} onChange={(routePoints)=>onPatch(crew.id,{routePoints})}/><label className="form-field"><span>Висота від, м</span><input type="number" value={entry.altitudeFrom} onChange={(event)=>onPatch(crew.id,{altitudeFrom:event.target.value})}/></label><label className="form-field"><span>Висота до, м</span><input type="number" value={entry.altitudeTo} onChange={(event)=>onPatch(crew.id,{altitudeTo:event.target.value})}/></label><PointTagsInput label="Район виконання — населені пункти" value={entry.areaPoints} onChange={(areaPoints)=>onPatch(crew.id,{areaPoints})}/><label className="form-field"><span>Завдання після «Бойове чергування»</span><Select ariaLabel={`Завдання екіпажу ${crew.name}`} value={entry.task} onChange={(task)=>onPatch(crew.id,{task})} options={FLIGHT_TASKS.map((value)=>({value,label:value}))}/></label><label className="form-field"><span>Початок</span><input type="time" value={entry.startTime} onChange={(event)=>onPatch(crew.id,{startTime:event.target.value})}/></label><label className="form-field"><span>Закінчення</span><input type="time" value={entry.endTime} onChange={(event)=>onPatch(crew.id,{endTime:event.target.value})}/></label></div>
            <div className="flight-crew__links"><Route/><span>Фактичний склад: {crew.actualMembers.length}</span><span>БпЛА: {crewUavs.length||crew.uavName||"не вказано"}</span><span>Автомобілі: {crewVehicles.length||"немає"}</span></div>
          </div>}
        </article>;})}
      </section>
    </div>
  </section>;
}
