import { Route } from "lucide-react";
import { Select } from "../../shared/ui/Select";
import type { Vehicle } from "../vehicles/types";
import { FLIGHT_TASKS } from "./flight-plan-model";
import { PointTagsInput } from "./PointTagsInput";
import type { Crew, Equipment, FlightPlanEntry, FlightPlanWeather, WorkshopProduct } from "./types";

const weatherFields: Array<[keyof FlightPlanWeather,string]> = [["temperature","Температура, °С"],["windFrom","Вітер від, м/с"],["windTo","Вітер до, м/с"],["gustFrom","Пориви від, м/с"],["gustTo","Пориви до, м/с"],["cloudiness","Хмарність, %"],["cloudHeight","Висота хмар, м"],["precipitation","Вірогідність опадів, %"]];

export function FlightPlanEntryFields({ crew, entry, vehicles, uavs, ammunition, workshopProducts, onPatch }: {
  crew: Crew;
  entry: FlightPlanEntry;
  vehicles: Vehicle[];
  uavs: Equipment[];
  ammunition: Equipment[];
  workshopProducts: WorkshopProduct[];
  onPatch: (patch: Partial<FlightPlanEntry>) => void;
}) {
  const crewVehicles=vehicles.filter((item)=>item.crewId===crew.id);
  const crewUavs=uavs.filter((item)=>item.crewId===crew.id);
  const ids=new Set(entry.actualMemberIds?.length?entry.actualMemberIds:crew.actualMembers.map((member)=>member.personnelId));
  const actualMembers=[...crew.members,...crew.actualMembers].filter((member,index,members)=>ids.has(member.personnelId)&&members.findIndex((candidate)=>candidate.personnelId===member.personnelId)===index);
  return <div className="flight-plan-editor__fields">
    <fieldset><legend>Фактичне забезпечення</legend><div className="flight-plan-actual-grid"><label className="form-field"><span>Фактичний командир екіпажу</span><Select ariaLabel={`Фактичний командир ${crew.name}`} value={entry.actualCommanderId?.toString()??""} onChange={(value)=>onPatch({actualCommanderId:value?Number(value):null})} options={actualMembers.map((member)=>({value:String(member.personnelId),label:`${member.fullName}${member.callsign?` · ${member.callsign}`:""}`}))}/></label>{crewVehicles.length>1&&<label className="form-field"><span>Фактичний автомобіль</span><Select ariaLabel={`Фактичний автомобіль ${crew.name}`} value={entry.actualVehicleId?.toString()??""} onChange={(value)=>onPatch({actualVehicleId:value?Number(value):null})} options={[{value:"",label:"Оберіть автомобіль"},...crewVehicles.map((vehicle)=>({value:String(vehicle.id),label:`${vehicle.name} · ${vehicle.registrationNumber}`}))]}/></label>}</div></fieldset>
    <fieldset><legend>БпЛА у плані польотів</legend><div className="flight-uav-selector">{crewUavs.map((uav)=>{const current=entry.uavSelections.find((item)=>item.equipmentId===uav.id);const patchQuantity=(key:"dayQuantity"|"nightQuantity",raw:number)=>{if(!current)return;const other=key==="dayQuantity"?current.nightQuantity:current.dayQuantity;const value=Math.max(0,Math.min(Number.isFinite(raw)?raw:0,uav.totalQuantity-other));onPatch({uavSelections:entry.uavSelections.map((item)=>item.equipmentId===uav.id?{...item,[key]:value}:item)});};return <article className={current?"selected":""} key={uav.id}><label><input type="checkbox" checked={!!current} onChange={()=>onPatch({uavSelections:current?entry.uavSelections.filter((item)=>item.equipmentId!==uav.id):[...entry.uavSelections,{equipmentId:uav.id,dayQuantity:uav.dayQuantity,nightQuantity:uav.nightQuantity}]})}/><span><b>{uav.name}</b><small>{uav.inventoryNumber||"Без номера"} · усього {uav.totalQuantity}</small></span></label>{current&&<div><label className="form-field"><span>Денні</span><input type="number" min="0" max={uav.totalQuantity-current.nightQuantity} value={current.dayQuantity} onChange={(event)=>patchQuantity("dayQuantity",Number(event.target.value))}/></label><label className="form-field"><span>Нічні</span><input type="number" min="0" max={uav.totalQuantity-current.dayQuantity} value={current.nightQuantity} onChange={(event)=>patchQuantity("nightQuantity",Number(event.target.value))}/></label></div>}</article>})}{!crewUavs.length&&<p>За екіпажем не закріплено жодного БпЛА.</p>}</div></fieldset>
    {entry.task==="Ураження противника"&&<fieldset><legend>Бойове навантаження</legend><label className="form-field form-field--wide"><span>Штатне БК або виріб Цукерні</span><Select ariaLabel={`Бойове навантаження ${crew.name}`} value={entry.payloadSelection?`${entry.payloadSelection.sourceType}:${entry.payloadSelection.sourceId}`:""} onChange={(value)=>{const [sourceType,sourceId]=value.split(":");onPatch({payloadSelection:value?{sourceType:sourceType as "equipment"|"workshop",sourceId:Number(sourceId)}:null});}} options={[{value:"",label:"Не обрано"},...ammunition.filter((item)=>item.weaponKind==="ammunition"&&item.stockQuantity>0).map((item)=>({value:`equipment:${item.id}`,label:`Штатне БК · ${item.name} · ${item.stockQuantity} ${item.measurementUnit}`})),...workshopProducts.filter((item)=>item.quantity>0).map((item)=>({value:`workshop:${item.id}`,label:`Цукерня · ${item.name} · ${item.quantity} ${item.measurementUnit}`}))]}/></label></fieldset>}
    <fieldset><legend>Погода цього етапу</legend><div className="flight-weather__grid">{weatherFields.map(([key,label])=><label className="form-field" key={key}><span>{label}</span><input type="number" value={entry.weather[key]} onChange={(event)=>onPatch({weather:{...entry.weather,[key]:event.target.value}})}/></label>)}</div></fieldset>
    <div className="flight-plan-editor__route"><PointTagsInput label="Маршрут — населені пункти" value={entry.routePoints} onChange={(routePoints)=>onPatch({routePoints})}/><label className="form-field"><span>Висота від, м</span><input type="number" value={entry.altitudeFrom} onChange={(event)=>onPatch({altitudeFrom:event.target.value})}/></label><label className="form-field"><span>Висота до, м</span><input type="number" value={entry.altitudeTo} onChange={(event)=>onPatch({altitudeTo:event.target.value})}/></label><PointTagsInput label="Район виконання — населені пункти" value={entry.areaPoints} onChange={(areaPoints)=>onPatch({areaPoints})}/><label className="form-field"><span>Завдання після «Бойове чергування»</span><Select ariaLabel={`Завдання екіпажу ${crew.name}`} value={entry.task} onChange={(task)=>onPatch({task})} options={FLIGHT_TASKS.map((value)=>({value,label:value}))}/></label><label className="form-field"><span>Початок</span><input type="time" value={entry.startTime} onChange={(event)=>onPatch({startTime:event.target.value})}/></label><label className="form-field"><span>Закінчення</span><input type="time" value={entry.endTime} onChange={(event)=>onPatch({endTime:event.target.value})}/></label></div>
    <div className="flight-crew__links"><Route/><span>Фактичний склад: {actualMembers.length}</span><span>БпЛА: {crewUavs.length||crew.uavName||"не вказано"}</span><span>Автомобілі: {crewVehicles.length||"немає"}</span></div>
  </div>;
}
