import { Crosshair, MapPin, Pencil, Plus, Radar, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ConfirmDialog } from "../../shared/ui/ConfirmDialog";
import { Modal } from "../../shared/ui/Modal";
import { useNotifications } from "../../shared/ui/NotificationProvider";
import { PageFrame } from "../../shared/ui/PageFrame";
import { PageTitle } from "../../shared/ui/PageTitle";
import { SearchInput } from "../../shared/ui/SearchInput";
import { Select } from "../../shared/ui/Select";
import { operationsService } from "./services/operationsService";
import type { Position, PositionDraft } from "./types";

const positionTypes: Position["positionType"][] = ["Основна", "Запасна", "Облаштовується", "Виявлена ворогом", "Зайнята суміжниками"];
const emptyDraft = (): PositionDraft => ({ name: "", positionType: "Основна", stripName: "", locality: "", battleOrder: "", sector: "", condition: "", conditionLevel: 0, fieldType: "", size: "", mgrs: "", suitableUavText: "", isActive: false, crewId: null, notes: "", uavIds: [] });
const typeClass = (type: Position["positionType"]) => type === "Основна" ? "primary" : type === "Запасна" ? "reserve" : type === "Облаштовується" ? "building" : type === "Виявлена ворогом" ? "exposed" : "allied";
function PositionsLoadingSkeleton(){return <section className="positions-loading-skeleton" aria-label="Завантаження позицій">{Array.from({length:6},(_,index)=><article className="panel" key={index}><header><i className="skeleton-line skeleton-line--icon"/><div><i className="skeleton-line skeleton-line--short"/><i className="skeleton-line skeleton-line--title"/></div></header><div className="skeleton-line skeleton-line--wide"/>{Array.from({length:4},(__,fact)=><i className="skeleton-line" key={fact}/>)}</article>)}</section>;}

export function PositionsPage() {
  const [items, setItems] = useState<Position[]>([]); const [query, setQuery] = useState(""); const [type, setType] = useState("Усі"); const [editing, setEditing] = useState<Position | null>(null); const [open, setOpen] = useState(false); const [draft, setDraft] = useState<PositionDraft>(emptyDraft); const [deleting, setDeleting] = useState<Position | null>(null); const [deletingBusy, setDeletingBusy] = useState(false); const [isLoading, setIsLoading] = useState(true); const { notify } = useNotifications();
  const reload = useCallback(() => { setIsLoading(true); void operationsService.listPositions().then(setItems).catch(() => notify("Не вдалося завантажити позиції.", "error")).finally(() => setIsLoading(false)); }, [notify]); useEffect(reload, [reload]);
  const filtered = useMemo(() => items.filter((item) => (type === "Усі" || item.positionType === type) && [item.name, item.positionType, item.stripName, item.locality, item.battleOrder, item.fieldType, item.crewName].join(" ").toLocaleLowerCase("uk").includes(query.toLocaleLowerCase("uk"))), [items, query, type]);
  const edit = (item?: Position) => { setEditing(item ?? null); setDraft(item ? { ...item } : emptyDraft()); setOpen(true); }; const close = () => { setOpen(false); setEditing(null); setDraft(emptyDraft()); };
  const savePosition = async () => { try { if (editing) await operationsService.updatePosition(editing.id, draft); else await operationsService.createPosition(draft); close(); reload(); notify("Позицію збережено.", "success"); } catch (error) { notify(typeof error === "string" ? error : "Не вдалося зберегти позицію.", "error"); } };
  const remove = async () => { if (!deleting) return; setDeletingBusy(true); try { await operationsService.deletePosition(deleting.id); setDeleting(null); reload(); notify("Позицію видалено.", "success"); } catch { notify("Не вдалося видалити позицію.", "error"); } finally { setDeletingBusy(false); } };
  return <PageFrame className="positions-page" header={<PageTitle title="Позиції" subtitle="Позиції підрозділу та їхній поточний стан" actions={<button className="button primary" onClick={() => edit()}><Plus />Додати позицію</button>} />} tools={<div className="table-tools main-tools"><SearchInput placeholder="Пошук за назвою, смугою, районом, БРО або екіпажем…" value={query} onChange={setQuery} /><Select ariaLabel="Тип позиції" value={type} onChange={setType} options={["Усі", ...positionTypes].map((value) => ({ value, label: value }))} /></div>}>
    <div className="positions-grid">{filtered.map((item) => <article className={`panel position-card position-card--${typeClass(item.positionType)}`} key={item.id}><header><span className="position-card__icon"><Crosshair /></span><div><span className="position-card__type">{item.positionType}</span><h2>{item.name}</h2></div><b className="position-condition">{item.conditionLevel}%<small>готовність</small></b></header><div className="position-tags">{item.stripName && <span>Смуга: {item.stripName}</span>}{item.battleOrder && <span>{item.battleOrder}</span>}{item.fieldType && <span>Поле: {item.fieldType}</span>}</div><div className="position-condition-scale"><i style={{ width: `${item.conditionLevel}%` }} /></div><dl><div><dt><MapPin />Район</dt><dd>{item.locality || "Не вказано"}</dd></div><div><dt><Radar />MGRS</dt><dd>{item.mgrs || "Не вказано"}</dd></div><div><dt>Екіпажі</dt><dd>{item.crewName || "Не використовується"}</dd></div><div><dt>Стан</dt><dd>{item.condition || "Без опису"}</dd></div></dl>{item.notes && <p className="position-notes">{item.notes}</p>}<footer><button className="button" onClick={() => edit(item)}><Pencil />Редагувати</button><button className="icon-button danger" title="Видалити позицію" onClick={() => setDeleting(item)}><Trash2 /></button></footer></article>)}</div>
    {isLoading && <div className="operations-loading-overlay"><PositionsLoadingSkeleton /></div>}
    {open && <Modal title={editing ? "Редагування позиції" : "Нова позиція"} onClose={close} className="position-editor"><div className="operation-editor__body"><label className="form-field"><span>Назва <b>*</b></span><input autoFocus value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} /></label><label className="form-field"><span>Тип</span><Select ariaLabel="Тип" value={draft.positionType} onChange={(positionType) => setDraft({ ...draft, positionType: positionType as Position["positionType"] })} options={positionTypes.map((value) => ({ value, label: value }))} /></label><label className="form-field"><span>Смуга</span><input value={draft.stripName} onChange={(e) => setDraft({ ...draft, stripName: e.target.value })} /></label><label className="form-field"><span>БРО</span><input value={draft.battleOrder} onChange={(e) => setDraft({ ...draft, battleOrder: e.target.value })} /></label><label className="form-field form-field--wide"><span>Стан · {draft.conditionLevel}%</span><input className="position-condition-input" type="range" min="0" max="100" step="5" value={draft.conditionLevel} onChange={(e) => setDraft({ ...draft, conditionLevel: Number(e.target.value) })} /><input value={draft.condition} onChange={(e) => setDraft({ ...draft, condition: e.target.value })} placeholder="Короткий опис стану" /></label><label className="form-field"><span>Район</span><input value={draft.locality} onChange={(e) => setDraft({ ...draft, locality: e.target.value })} /></label><label className="form-field form-field--wide"><span>Орієнтовні координати MGRS</span><input value={draft.mgrs} onChange={(e) => setDraft({ ...draft, mgrs: e.target.value })} placeholder="36U UV 12000 67000" /><small>Останні три цифри двох п’ятизначних груп зберігаються як 000.</small></label><label className="form-field"><span>Тип поля</span><input value={draft.fieldType} onChange={(e) => setDraft({ ...draft, fieldType: e.target.value })} /></label><label className="form-field form-field--wide"><span>Коментар</span><textarea value={draft.notes} onChange={(e) => setDraft({ ...draft, notes: e.target.value })} /></label></div><footer className="modal-actions"><button className="button" onClick={close}>Скасувати</button><button className="button primary" onClick={() => void savePosition()}>Зберегти позицію</button></footer></Modal>}
    {deleting && <ConfirmDialog title="Видалити позицію?" message={`Позицію «${deleting.name}» буде видалено. Екіпажі, які її використовують, залишаться без обраної позиції.`} confirmLabel="Видалити" onConfirm={() => void remove()} onCancel={() => setDeleting(null)} busy={deletingBusy} />}
  </PageFrame>;
}
