import { renderAsync } from "docx-preview";
import { save } from "@tauri-apps/plugin-dialog";
import { FileOutput, Plus, RefreshCw, Trash2 } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { AppSettings } from "../../shared/types/domain";
import { PageFrame } from "../../shared/ui/PageFrame";
import { PageTitle } from "../../shared/ui/PageTitle";
import { useNotifications } from "../../shared/ui/NotificationProvider";
import { settingsService } from "../settings/services/settingsService";
import { operationsService } from "./services/operationsService";
import { summaryReportService } from "./services/summaryReportService";
import { buildSummaryDocument, canOpenNextReport, carryForwardSummary, defaultSummaryManual, displayDate, initialReportDate, shiftDate, type SummaryCompositionItem, type SummaryDutyItem, type SummaryManual, type SummaryPositionItem, type SummaryTextItem } from "./summary-report-model";
import type { Crew, FlightJournalEntry, FlightPlanRequest, Position, StaffingRecord } from "./types";

const parseDraft = (value: string | null): SummaryManual | null => { try { if (!value) return null; const defaults = defaultSummaryManual(); const stored = JSON.parse(value) as Partial<SummaryManual>; const duties = (items: unknown): SummaryDutyItem[] => Array.isArray(items) ? items.map((item) => { const duty = item as Partial<SummaryDutyItem> & { text?: string }; const matches = duty.text?.match(/(\d{2}:\d{2}).*?(\d{2}\.\d{2}\.\d{4}).*?(\d{2}:\d{2}).*?(\d{2}\.\d{2}\.\d{4})/u); return { id: duty.id || crypto.randomUUID(), personnelId: duty.personnelId ?? null, startTime: duty.startTime || matches?.[1] || "", startDate: duty.startDate || matches?.[2]?.split(".").reverse().join("-") || "", endTime: duty.endTime || matches?.[3] || "", endDate: duty.endDate || matches?.[4]?.split(".").reverse().join("-") || "" }; }) : []; return { ...defaults, ...stored, enemyLosses: { ...defaults.enemyLosses, ...stored.enemyLosses }, completeness: { ...defaults.completeness, ...stored.completeness }, personnelLosses: { ...defaults.personnelLosses, ...stored.personnelLosses }, equipmentLosses: { ...defaults.equipmentLosses, ...stored.equipmentLosses }, commandDuties: duties(stored.commandDuties), guardDuties: duties(stored.guardDuties) }; } catch { return null; } };
const blankSettings = (): AppSettings => ({ mainSigner: { fullName: "", rank: "", position: "" }, commander: { fullName: "", rank: "", position: "" }, chief: { fullName: "", rank: "", position: "" }, deputyPpp: { fullName: "", rank: "", position: "" }, deputyArmament: { fullName: "", rank: "", position: "" }, deputyRear: { fullName: "", rank: "", position: "" }, fuelChief: { fullName: "", rank: "", position: "" }, signerRoles: [], unit: { kind: "Інше", shortName: "", authorizedStrength: 0 } });
const parseSnapshot = (value: string | null): FlightPlanRequest | null => { try { return value ? JSON.parse(value) as FlightPlanRequest : null; } catch { return null; } };
const enemyLossLabels: Array<[string, string]> = [["personnel", "Особовий склад — всього"], ["irreversible", "Безповоротні"], ["sanitary", "Санітарні"], ["captured", "Полон"], ["ovt", "ОВТ — всього"], ["ovtDestroyed", "ОВТ знищено"], ["ovtDamaged", "ОВТ пошкоджено"], ["tanks", "Танки"], ["tanksDestroyed", "Танки знищено"], ["tanksDamaged", "Танки пошкоджено"], ["afv", "ББМ"], ["afvDestroyed", "ББМ знищено"], ["afvDamaged", "ББМ пошкоджено"], ["artillery", "ГіМ"], ["artilleryDestroyed", "ГіМ знищено"], ["artilleryDamaged", "ГіМ пошкоджено"], ["mlrs", "РСЗВ"], ["mlrsDestroyed", "РСЗВ знищено"], ["mlrsDamaged", "РСЗВ пошкоджено"], ["reb", "РЕБ"], ["rebDestroyed", "РЕБ знищено"], ["rebDamaged", "РЕБ пошкоджено"], ["vehicles", "АТТ"], ["vehiclesDestroyed", "АТТ знищено"], ["vehiclesDamaged", "АТТ пошкоджено"], ["aircraft", "Літаки / гелікоптери"], ["aircraftDestroyed", "Авіація знищена"], ["aircraftDamaged", "Авіація пошкоджена"], ["uav", "БпЛА"], ["uavDestroyed", "БпЛА знищено"], ["uavDamaged", "БпЛА пошкоджено"], ["airDefence", "Засоби ППО"], ["communications", "Засоби зв’язку"]];
const personnelLossLabels: Array<[string, string]> = [["total", "Загальні втрати"], ["irreversible", "Безповоротні"], ["combatIrreversible", "Бойові безповоротні"], ["killed", "Загинули"], ["diedFromWounds", "Померли від ран"], ["other", "Інші"], ["temporary", "Тимчасові"], ["combatTemporary", "Бойові тимчасові"], ["wounded", "Санітарні бойові"], ["captured", "Полон"], ["missing", "Зникли безвісти"], ["deserters", "Дезертири"], ["szch", "СЗЧ"]];
const equipmentLossLabels: Array<[string, string]> = [["total", "ОВТ — всього"], ["destroyed", "Знищено"], ["lost", "Втрачено"], ["damaged", "Пошкоджено"], ["tanks", "Танки"], ["afv", "ББМ"], ["artillery", "ГіМ"], ["airDefence", "Засоби ППО"], ["vehicles", "АТ"], ["reb", "Засоби РЕБ"], ["communications", "Засоби зв’язку"], ["uav", "БпЛА"]];
const enemyExtendedLossLabels: Array<[string, string]> = [...enemyLossLabels, ["uavLoitering", "Баражуючі боєприпаси"], ["uavMolniya", "Молнія"], ["uavLancet", "Ланцет"], ["uavReb", "БпЛА, посаджені РЕБ"], ["specialEquipment", "Спеціальна техніка"], ["specialEquipmentDestroyed", "Спецтехніка знищена"], ["specialEquipmentDamaged", "Спецтехніка пошкоджена"], ["reconEquipment", "Засоби розвідки"], ["reconEquipmentDestroyed", "Засоби розвідки знищено"], ["reconEquipmentDamaged", "Засоби розвідки пошкоджено"], ["uavControl", "ПУ БпЛА"], ["uavControlDestroyed", "ПУ БпЛА знищено"], ["uavControlDamaged", "ПУ БпЛА пошкоджено"], ["communicationsDestroyed", "Зв’язок знищено"], ["communicationsDamaged", "Зв’язок пошкоджено"], ["commandPosts", "Пункти управління"], ["shelters", "Укриття"], ["commandPostsDestroyed", "Пункти управління знищено"], ["commandPostsDamaged", "Пункти управління пошкоджено"], ["sheltersDamaged", "Пошкоджено укриттів"], ["ammoDepots", "Склади боєприпасів"], ["fuelDepots", "Склади ПММ"], ["depotsDestroyed", "Склади знищено"], ["depotsDamaged", "Склади пошкоджено"]];
const equipmentExtendedLossLabels: Array<[string, string]> = [...equipmentLossLabels, ["tanksDestroyed", "Танки знищено"], ["tanksDamaged", "Танки пошкоджено"], ["afvDestroyed", "ББМ знищено"], ["afvDamaged", "ББМ пошкоджено"], ["artilleryDestroyed", "ГіМ знищено"], ["artilleryDamaged", "ГіМ пошкоджено"], ["airDefenceDestroyed", "ППО знищено"], ["airDefenceDamaged", "ППО пошкоджено"], ["vehiclesDestroyed", "АТ знищено"], ["vehiclesDamaged", "АТ пошкоджено"], ["rebDestroyed", "РЕБ знищено"], ["communicationsDestroyed", "Зв’язок знищено"], ["uavLost", "БпЛА втрачено"], ["uavDamaged", "БпЛА пошкоджено"]];

function ItemEditor({ title, items, onChange }: { title: string; items: SummaryTextItem[]; onChange: (items: SummaryTextItem[]) => void }) {
  return <section className="summary-editor-block"><header><b>{title}</b><button className="icon-button" aria-label={`Додати: ${title}`} onClick={() => onChange([...items, { id: crypto.randomUUID(), text: "" }])}><Plus /></button></header>{items.length ? items.map((item) => <div className="summary-object" key={item.id}><textarea value={item.text} onChange={(event) => onChange(items.map((value) => value.id === item.id ? { ...value, text: event.target.value } : value))} /><button className="icon-button danger" aria-label="Видалити" onClick={() => onChange(items.filter((value) => value.id !== item.id))}><Trash2 /></button></div>) : <small>Об’єктів немає. Додайте за потреби.</small>}</section>;
}

function DutyEditor({ title, items, people, positionPersonnel, onChange }: { title: string; items: SummaryDutyItem[]; people: StaffingRecord[]; positionPersonnel: Set<number>; onChange: (items: SummaryDutyItem[]) => void }) {
  const available = people.filter((person) => person.personnelId > 0 && !positionPersonnel.has(person.personnelId));
  const set = <K extends keyof SummaryDutyItem>(id: string, key: K, value: SummaryDutyItem[K]) => onChange(items.map((item) => item.id === id ? { ...item, [key]: value } : item));
  return <section className="summary-editor-block"><header><div><b>{title}</b><small>Кожне чергування є окремим пунктом документа.</small></div><button className="icon-button" aria-label={`Додати: ${title}`} onClick={() => onChange([...items, { id: crypto.randomUUID(), personnelId: null, startDate: "", startTime: "", endDate: "", endTime: "" }])}><Plus /></button></header>{items.length ? items.map((item) => <div className="summary-duty-object" key={item.id}><select aria-label="Військовослужбовець" value={item.personnelId ?? ""} onChange={(event) => set(item.id, "personnelId", event.target.value ? Number(event.target.value) : null)}><option value="">Оберіть військовослужбовця</option>{available.map((person) => <option key={person.personnelId} value={person.personnelId}>{person.fullName} · {person.rank}</option>)}</select><div className="summary-duty-period"><label><span>Початок</span><input type="date" value={item.startDate} onChange={(event) => set(item.id, "startDate", event.target.value)} /><input type="time" value={item.startTime} onChange={(event) => set(item.id, "startTime", event.target.value)} /></label><label><span>Завершення</span><input type="date" value={item.endDate} onChange={(event) => set(item.id, "endDate", event.target.value)} /><input type="time" value={item.endTime} onChange={(event) => set(item.id, "endTime", event.target.value)} /></label></div><button className="icon-button danger" aria-label="Видалити" onClick={() => onChange(items.filter((value) => value.id !== item.id))}><Trash2 /></button></div>) : <small>Об’єктів немає. Люди, які зазначені на позиції у плані польотів, тут недоступні.</small>}</section>;
}

function CompositionEditor({ automatic, value, onChange }: { automatic: SummaryCompositionItem[]; value: SummaryCompositionItem[] | null; onChange: (items: SummaryCompositionItem[] | null) => void }) {
  const items = value ?? automatic; const edit = (id: string, patch: Partial<SummaryCompositionItem>) => onChange(items.map((item) => item.id === id ? { ...item, ...patch } : item));
  return <section className="summary-editor-block"><header><div><b>2.2. Склад та бойовий порядок</b><small>Один блок формує один абзац у документі.</small></div><button className="icon-button" aria-label="Додати групу екіпажів" onClick={() => onChange([...items, { id: crypto.randomUUID(), count: "1", uavKind: "екіпажі розвідувальних БпЛА літакового типу", battleOrder: "", workStrip: "" }])}><Plus /></button></header>{items.map((item) => <div className="summary-structured-object" key={item.id}><label><span>Кількість екіпажів</span><input inputMode="numeric" value={item.count} onChange={(event) => edit(item.id, { count: event.target.value.replace(/\D/gu, "") })} /></label><label><span>Тип екіпажів і БпЛА</span><input value={item.uavKind} onChange={(event) => edit(item.id, { uavKind: event.target.value })} /></label><label><span>БрО, у межах якої виконують завдання</span><input value={item.battleOrder} onChange={(event) => edit(item.id, { battleOrder: event.target.value })} /></label><label><span>Смуга роботи / підрозділи взаємодії</span><input value={item.workStrip} onChange={(event) => edit(item.id, { workStrip: event.target.value })} /></label><button className="icon-button danger" aria-label="Видалити групу" onClick={() => onChange(items.filter((value) => value.id !== item.id))}><Trash2 /></button></div>)}<button className="button" disabled={value === null} onClick={() => onChange(null)}>Оновити з плану польотів</button></section>;
}

function PositionEditor({ automatic, value, onChange }: { automatic: SummaryPositionItem[]; value: SummaryPositionItem[] | null; onChange: (items: SummaryPositionItem[] | null) => void }) {
  const items = value ?? automatic; const edit = (id: string, patch: Partial<SummaryPositionItem>) => onChange(items.map((item) => item.id === id ? { ...item, ...patch } : item));
  return <section className="summary-editor-block"><header><div><b>2.2. Положення підрозділів</b><small>Позиції автоматично групуються за смугою роботи.</small></div><button className="icon-button" aria-label="Додати позицію" onClick={() => onChange([...items, { id: crypto.randomUUID(), workStrip: "", uavName: "", positionName: "", mgrs: "", locality: "" }])}><Plus /></button></header>{items.map((item) => <div className="summary-structured-object summary-structured-object--position" key={item.id}>{([['workStrip','Смуга роботи'],['uavName','Назва БпАК'],['positionName','Назва позиції'],['mgrs','Координати MGRS'],['locality','Район населеного пункту']] as const).map(([key,label]) => <label key={key}><span>{label}</span><input value={item[key]} onChange={(event) => edit(item.id, { [key]: event.target.value })} /></label>)}<button className="icon-button danger" aria-label="Видалити позицію" onClick={() => onChange(items.filter((value) => value.id !== item.id))}><Trash2 /></button></div>)}<button className="button" disabled={value === null} onClick={() => onChange(null)}>Оновити з плану польотів</button></section>;
}

function AutomaticItemEditor({ title, automatic, value, onChange }: { title: string; automatic: SummaryTextItem[]; value: SummaryTextItem[] | null; onChange: (items: SummaryTextItem[] | null) => void }) {
  const items = value ?? automatic;
  return <section className="summary-editor-block"><header><div><b>{title}</b><small>Кожен блок відповідає одному екіпажу на позиції; повторні вильоти об’єднані.</small></div><button className="icon-button" aria-label={`Додати: ${title}`} onClick={() => onChange([...items, { id: crypto.randomUUID(), text: "" }])}><Plus /></button></header>{items.map((item) => <div className="summary-object" key={item.id}><textarea value={item.text} onChange={(event) => onChange(items.map((value) => value.id === item.id ? { ...value, text: event.target.value } : value))} /><button className="icon-button danger" aria-label="Видалити" onClick={() => onChange(items.filter((value) => value.id !== item.id))}><Trash2 /></button></div>)}<button className="button" disabled={value === null} onClick={() => onChange(null)}>Оновити з плану та журналу польотів</button></section>;
}

function EventEditor({ items, onChange }: { items: SummaryTextItem[]; onChange: (items: SummaryTextItem[]) => void }) {
  const set = (id: string, patch: Partial<SummaryTextItem>) => onChange(items.map((item) => item.id === id ? { ...item, ...patch } : item));
  return <section className="summary-editor-block"><header><div><b>3.3. Події, проведені за звітний період</b><small>Додавайте лише фактичні події. Програма не створює довільних формулювань.</small></div><button className="icon-button" aria-label="Додати подію" onClick={() => onChange([...items, { id: crypto.randomUUID(), date: "", time: "", text: "" }])}><Plus /></button></header>{items.map((item) => <div className="summary-event-object" key={item.id}><label><span>Дата</span><input type="date" value={item.date || ""} onChange={(event) => set(item.id, { date: event.target.value })} /></label><label><span>Час</span><input type="time" value={item.time || ""} onChange={(event) => set(item.id, { time: event.target.value })} /></label><label><span>Текст події</span><textarea value={item.text} onChange={(event) => set(item.id, { text: event.target.value })} /></label><button className="icon-button danger" aria-label="Видалити подію" onClick={() => onChange(items.filter((value) => value.id !== item.id))}><Trash2 /></button></div>)}</section>;
}

function RotationEventEditor({ events, included, edits, onIncluded, onEdits }: { events: SummaryTextItem[]; included: string[]; edits: Record<string, string>; onIncluded: (ids: string[]) => void; onEdits: (value: Record<string, string>) => void }) {
  return <section className="summary-editor-block"><header><div><b>3.3. Підтверджені ротації з плану польотів</b><small>У документ потрапляють тільки позначені події.</small></div><span className="source-badge">автоматично</span></header>{events.length ? events.map((item) => { const checked = included.includes(item.id); return <div className={`summary-rotation-event ${checked ? "is-included" : ""}`} key={item.id}><label className="check-row"><input type="checkbox" checked={checked} onChange={() => onIncluded(checked ? included.filter((id) => id !== item.id) : [...included, item.id])} /><span>Вивести у підсумковому</span></label><textarea disabled={!checked} value={edits[item.id] ?? item.text} onChange={(event) => onEdits({ ...edits, [item.id]: event.target.value })} /></div>; }) : <small>У знімках плану польотів немає підтверджених змін складу.</small>}</section>;
}

function NumberGrid({ title, values, labels, onChange }: { title: string; values: Record<string, string>; labels: Array<[string, string]>; onChange: (value: Record<string, string>) => void }) {
  return <section className="summary-editor-block"><header><b>{title}</b></header><div className="summary-number-grid">{labels.map(([key, label]) => <label className="form-field" key={key}><span>{label}</span><input inputMode="numeric" value={values[key] ?? ""} onChange={(event) => onChange({ ...values, [key]: event.target.value.replace(/[^0-9]/gu, "") })} /></label>)}</div></section>;
}

export function SummaryReportPage() {
  const { notify } = useNotifications();
  const [reportDate, setReportDate] = useState(initialReportDate);
  const [manual, setManual] = useState<SummaryManual>(defaultSummaryManual);
  const [settings, setSettings] = useState<AppSettings>(blankSettings);
  const [crews, setCrews] = useState<Crew[]>([]);
  const [positions, setPositions] = useState<Position[]>([]);
  const [journal, setJournal] = useState<FlightJournalEntry[]>([]);
  const [staffing, setStaffing] = useState<StaffingRecord[]>([]);
  const [snapshots, setSnapshots] = useState<Array<FlightPlanRequest | null>>([]);
  const [ready, setReady] = useState(false);
  const [exporting, setExporting] = useState(false);
  const [previewError, setPreviewError] = useState("");
  const [lastPath, setLastPath] = useState("");
  const [, setClock] = useState(() => Date.now());
  const previewRef = useRef<HTMLDivElement>(null);

  const load = useCallback(async (date = reportDate) => {
    try {
      const [draft, nextSettings, nextCrews, nextPositions, nextJournal, nextStaffing, previousSnapshot, currentSnapshot] = await Promise.all([summaryReportService.loadDraft(date), settingsService.get(), operationsService.listCrews(), operationsService.listPositions(), operationsService.listFlightJournalEntries(), operationsService.listStaffingRecords(), operationsService.getFlightPlanSnapshot(shiftDate(date, -1)), operationsService.getFlightPlanSnapshot(date)]);
      setSettings(nextSettings); setCrews(nextCrews); setPositions(nextPositions); setJournal(nextJournal); setStaffing(nextStaffing); setSnapshots([parseSnapshot(previousSnapshot), parseSnapshot(currentSnapshot)]);
      setManual(parseDraft(draft.current) ?? carryForwardSummary(parseDraft(draft.previous)));
      setReady(true);
    } catch { notify("Не вдалося завантажити підсумкове донесення.", "error"); }
  }, [notify, reportDate]);
  useEffect(() => { setReady(false); void load(reportDate); }, [load, reportDate]);
  useEffect(() => { const refresh = () => { if (document.visibilityState === "visible") void load(reportDate); }; window.addEventListener("focus", refresh); return () => window.removeEventListener("focus", refresh); }, [load, reportDate]);
  useEffect(() => { const timer = window.setInterval(() => { const now = new Date(); setClock(now.getTime()); const automaticDate = initialReportDate(now); if (automaticDate > reportDate) setReportDate(automaticDate); }, 60_000); return () => window.clearInterval(timer); }, [reportDate]);
  useEffect(() => { if (!ready) return; const timer = window.setTimeout(() => void summaryReportService.saveDraft(reportDate, JSON.stringify(manual)).catch(() => notify("Не вдалося автоматично зберегти правки донесення.", "error")), 350); return () => window.clearTimeout(timer); }, [manual, notify, ready, reportDate]);

  const positionPersonnel = useMemo(() => new Set(snapshots.flatMap((snapshot) => snapshot?.entries.flatMap((entry) => entry.actualMemberIds ?? []) ?? [])), [snapshots]);
  const built = useMemo(() => buildSummaryDocument({ reportDate, manual, settings, crews, positions, journal, snapshots, staffing }), [crews, journal, manual, positions, reportDate, settings, snapshots, staffing]);
  useEffect(() => {
    if (!ready || !previewRef.current) return;
    let cancelled = false; const target = previewRef.current; setPreviewError("");
    const timer = window.setTimeout(() => void summaryReportService.render(built.document).then((bytes) => { if (cancelled) return; target.replaceChildren(); return renderAsync(new Blob([new Uint8Array(bytes)]), target, target, { inWrapper: true, breakPages: true, renderHeaders: true, renderFooters: true, useBase64URL: true }); }).catch(() => { if (!cancelled) setPreviewError("Не вдалося оновити перегляд документа."); }), 250);
    return () => { cancelled = true; window.clearTimeout(timer); };
  }, [built.document, ready]);

  const patch = <K extends keyof SummaryManual>(key: K, value: SummaryManual[K]) => setManual((current) => ({ ...current, [key]: value }));
  const exportDocument = async () => {
    if (built.warnings.length) { notify("Спочатку заповніть критичні поля, перелічені над редактором.", "error"); return; }
    const shortName = settings.unit.shortName || "Підрозділ";
    const defaultPath = `Підсумкове бойове донесення_${shortName}_${displayDate(reportDate)}.docx`;
    const selected = await save({ title: "Зберегти підсумкове донесення", defaultPath, filters: [{ name: "Документ Word", extensions: ["docx"] }] });
    if (!selected) return; const path = selected.endsWith(".docx") ? selected : `${selected}.docx`;
    setExporting(true); try { await summaryReportService.saveDraft(reportDate, JSON.stringify(manual)); await summaryReportService.export(path, built.document); setLastPath(path); notify("Підсумкове донесення збережено.", "success"); } catch (error) { notify(typeof error === "string" ? error : "Не вдалося створити донесення.", "error"); } finally { setExporting(false); }
  };
  const moveNext = () => setReportDate(shiftDate(reportDate, 1));

  return <PageFrame className="summary-report-page" header={<PageTitle title="Підсумкове донесення" subtitle={`Звітний період: ${displayDate(shiftDate(reportDate, -1))} 18:01 — ${displayDate(reportDate)} 18:00`} actions={<div className="summary-title-actions">{canOpenNextReport(reportDate) && <button className="button" onClick={moveNext}>Перейти до нового донесення</button>}<button className="button primary" disabled={exporting || !ready} onClick={() => void exportDocument()}><FileOutput />{exporting ? "Створення…" : "Створити підсумкове донесення"}</button></div>} />}>
    <div className="summary-report-layout">
      <section className="panel summary-preview"><header><div><b>Документ за {displayDate(reportDate)}</b><small>Перегляд змінюється разом із даними програми та ручними правками.</small></div><button className="icon-button" aria-label="Оновити" onClick={() => void load()}><RefreshCw /></button></header><div ref={previewRef} className="summary-preview__document">{previewError && <div className="empty-state">{previewError}</div>}</div></section>
      <aside className="summary-controls">
        {built.warnings.length > 0 && <section className="summary-warnings"><b>Потрібно заповнити перед створенням</b>{built.warnings.map((warning) => <span key={warning}>{warning}</span>)}</section>}
        <section className="summary-editor-block"><header><b>Параметри документа</b><span className="source-badge">вручну</span></header><label className="form-field"><span>Номер донесення</span><input value={manual.reportNumber} onChange={(event) => patch("reportNumber", event.target.value)} /></label><small>Дата: {displayDate(reportDate)} · Прим. № 1</small></section>
        <details><summary>Повні числові показники втрат противника</summary><NumberGrid title="Усі показники з шаблону" values={manual.enemyLosses} onChange={(value) => patch("enemyLosses", value)} labels={enemyExtendedLossLabels} /></details>
        <details open><summary>1–2. Обстановка, склад і положення</summary><NumberGrid title="1. Орієнтовні втрати противника" values={manual.enemyLosses} onChange={(value) => patch("enemyLosses", value)} labels={[["personnel", "Особовий склад"], ["tanks", "Танки"], ["afv", "ББМ"], ["artillery", "Артсистеми"], ["uav", "БпЛА — всього"], ["uavLoitering", "Баражуючі боєприпаси"], ["uavMolniya", "Молнія"], ["uavLancet", "Ланцет"], ["uavDamaged", "БпЛА пошкоджено"], ["commandPosts", "Пункти управління"], ["shelters", "Укриття"], ["commandPostsDestroyed", "Пункти управління знищено"], ["commandPostsDamaged", "Пункти управління пошкоджено"], ["sheltersDamaged", "Укриття пошкоджено"], ["vehicles", "Автотехніка"]]} /><section className="summary-editor-block"><header><b>2.1. Зміни в складі та положенні</b><span className="source-badge">без змін</span></header><label className="check-row"><input type="checkbox" checked={manual.compositionOverride} onChange={(event) => patch("compositionOverride", event.target.checked)} /><span>Вказати зміни вручну</span></label>{manual.compositionOverride && <textarea value={manual.compositionChanges} onChange={(event) => patch("compositionChanges", event.target.value)} />}</section><CompositionEditor automatic={built.objects.compositionItems} value={manual.compositionItems} onChange={(value) => patch("compositionItems", value)} /><section className="summary-editor-block"><header><div><b>2.2. Укомплектованість</b><small>Поля підставляються у фразу шаблону в зазначеному вигляді.</small></div><span className="source-badge">вручну</span></header>{([['personnel','Особовий склад, %'],['automotive','Автомобільна техніка, %'],['uavType','Вид БпАК у дужках'],['uav','БпАК, %'],['zbbr','ЗББР, %'],['fuel','ПММ, %']] as const).map(([key,label]) => <label className="form-field" key={key}><span>{label}</span><input value={manual.completeness[key]} onChange={(event) => patch("completeness", { ...manual.completeness, [key]: event.target.value })} /></label>)}</section><section className="summary-editor-block"><header><div><b>2.2. Управління підрозділами здійснюється</b><small>Буде використано у фразі: «КСП … – [околиці] населеного пункту …».</small></div></header><label className="form-field"><span>Які саме околиці населеного пункту КСП</span><input value={manual.kspOutskirts} onChange={(event) => patch("kspOutskirts", event.target.value)} placeholder="південні околиці" /></label></section><PositionEditor automatic={built.objects.positionItems} value={manual.positionItems} onChange={(value) => patch("positionItems", value)} /></details>
        <details><summary>3.2. Дії противника</summary><section className="summary-editor-block"><header><b>Противником нанесено</b></header><div className="summary-number-grid">{([['rocketStrikes','Ракетних ударів'],['airStrikes','Авіаційних ударів'],['va','ВА'],['sha','ША'],['aa','АА']] as const).map(([key,label]) => <label className="form-field" key={key}><span>{label}</span><input inputMode="numeric" value={manual[key]} onChange={(event) => patch(key, event.target.value.replace(/[^0-9]/gu, ""))} /></label>)}</div><label className="check-row"><input type="checkbox" checked={manual.enemyAssault} onChange={(event) => patch("enemyAssault", event.target.checked)} />Противник проводив наступальні дії</label>{manual.enemyAssault && <textarea value={manual.enemyAssaultText} onChange={(event) => patch("enemyAssaultText", event.target.value)} />}</section><section className="summary-editor-block"><header><div><b>Противник здійснив обстріли</b><small>Кожен обстріл формує окремий рядок таблиці.</small></div><button className="icon-button" onClick={() => patch("shellings", [...manual.shellings, { id: crypto.randomUUID(), time: "", shellingType: "", target: "", direction: "", response: "" }])}><Plus /></button></header>{manual.shellings.map((row) => <div className="summary-shelling" key={row.id}>{([['time','Час'],['shellingType','Вид обстрілу'],['target','По чому нанесено'],['direction','Звідки / напрямок'],['response','Вжиті заходи']] as const).map(([key,label]) => <label key={key}><span>{label}</span><input value={row[key]} onChange={(event) => patch("shellings", manual.shellings.map((item) => item.id === row.id ? { ...item, [key]: event.target.value } : item))} /></label>)}<button className="icon-button danger" onClick={() => patch("shellings", manual.shellings.filter((item) => item.id !== row.id))}><Trash2 /></button></div>)}</section></details>
        <details><summary>3.3–4. Робота підрозділу</summary><div className="summary-auto-note"><span className="source-badge">план польотів</span><span className="source-badge">журнал польотів</span><span className="source-badge">ротації</span></div><section className="summary-editor-block"><header><b>3.3. Наступальні (штурмові) дії</b></header><label className="check-row"><input type="checkbox" checked={manual.ownAssault} onChange={(event) => patch("ownAssault", event.target.checked)} />Підрозділ проводив наступальні дії</label>{manual.ownAssault && <textarea value={manual.ownAssaultText} onChange={(event) => patch("ownAssaultText", event.target.value)} />}</section><AutomaticItemEditor title="3.3. Польоти за смугами, позиціями та екіпажами" automatic={built.objects.flightItems} value={manual.flightItems} onChange={(value) => patch("flightItems", value)} /><DutyEditor title="3.3. Позмінне управління боєм на КСП" items={manual.commandDuties} people={staffing} positionPersonnel={positionPersonnel} onChange={(value) => patch("commandDuties", value)} /><DutyEditor title="3.3. Позмінна охорона та оборона КСП" items={manual.guardDuties} people={staffing} positionPersonnel={positionPersonnel} onChange={(value) => patch("guardDuties", value)} /><RotationEventEditor events={built.objects.rotationEvents} included={manual.includedAutoEventIds} edits={manual.autoEventEdits} onIncluded={(value) => patch("includedAutoEventIds", value)} onEdits={(value) => patch("autoEventEdits", value)} /><EventEditor items={manual.manualEvents} onChange={(value) => patch("manualEvents", value)} />{([["commissionsOverride", "commissions", "3.4. Робота комісій"], ["fortificationOverride", "fortification", "3.5. Фортифікаційне обладнання"], ["dzvinOverride", "dzvin", "4. Система АС «ДЗВІН»"]] as const).map(([toggle, field, title]) => <section className="summary-editor-block" key={field}><label className="check-row"><input type="checkbox" checked={manual[toggle]} onChange={(event) => patch(toggle, event.target.checked)} />{title}: змінити текст вручну</label>{manual[toggle] && <textarea value={manual[field]} onChange={(event) => patch(field, event.target.value)} />}</section>)}</details>
        <details><summary>5. Основні завдання</summary><ItemEditor title="5. Завдання на наступну добу" items={manual.nextTasks} onChange={(value) => patch("nextTasks", value)} /></details>
        <details><summary>Повні числові показники власних втрат</summary><NumberGrid title="Особовий склад" values={manual.personnelLosses} onChange={(value) => patch("personnelLosses", value)} labels={personnelLossLabels} /><NumberGrid title="ОВТ" values={manual.equipmentLosses} onChange={(value) => patch("equipmentLosses", value)} labels={equipmentExtendedLossLabels} /></details>
        <details><summary>6–7. Втрати та витрати</summary><NumberGrid title="6.1. Втрати особового складу" values={manual.personnelLosses} onChange={(value) => patch("personnelLosses", value)} labels={[["killed", "Загинуло"], ["wounded", "Поранено"], ["missing", "Зникло"], ["captured", "Полон"], ["sick", "Захворіло"]]} /><NumberGrid title="6.2. Втрати техніки" values={manual.equipmentLosses} onChange={(value) => patch("equipmentLosses", value)} labels={[["destroyed", "Знищено"], ["damaged", "Пошкоджено"], ["lost", "Втрачено"]]} /><section className="summary-editor-block"><label className="form-field"><span>6.2. Деталі втрат техніки</span><textarea value={manual.equipmentLossesDetails} onChange={(event) => patch("equipmentLossesDetails", event.target.value)} /></label><label className="form-field"><span>7. Витрати боєприпасів</span><textarea value={manual.ammunitionExpenses} onChange={(event) => patch("ammunitionExpenses", event.target.value)} /></label></section></details>
        <details><summary>8. Проблемні та інші питання</summary><section className="summary-editor-block"><label className="form-field"><span>Проблемні питання</span><textarea value={manual.problems} onChange={(event) => patch("problems", event.target.value)} /></label></section><ItemEditor title="Інші питання" items={manual.otherIssues} onChange={(value) => patch("otherIssues", value)} /></details>
        {lastPath && <button className="button full" onClick={() => void summaryReportService.open(lastPath)}>Відкрити створений DOCX</button>}
      </aside>
    </div>
  </PageFrame>;
}
