export type EquipmentCategory = "generator" | "uav" | "communications" | "weapon_ammo";

export type CrewMember = { personnelId: number; fullName: string; rank: string; position: string; callsign: string; currentLocation?: string };
export type Crew = {
  id: number;
  name: string;
  platoon: string;
  positionName: string;
  reconnaissanceArea: string;
  unitType: string;
  companyName: string;
  battleOrder: string;
  sector: string;
  officialStrength: number;
  workingStrength: number;
  positionId: number | null;
  status: string;
  uavName: string;
  uavType: string;
  primaryUavId?: number | null;
  functionalDuties: string;
  currentLocation: string;
  notes: string;
  memberCount: number;
  members: CrewMember[];
  actualMembers: CrewMember[];
};
export type CrewDraft = {
  name: string;
  platoon: string;
  positionName: string;
  reconnaissanceArea: string;
  unitType: string;
  companyName: string;
  battleOrder: string;
  sector: string;
  officialStrength: number;
  workingStrength: number;
  positionId: number | null;
  status: string;
  uavName: string;
  uavType: string;
  primaryUavId?: number | null;
  functionalDuties: string;
  currentLocation: string;
  notes: string;
  memberIds: number[];
  actualMemberIds: number[];
};
export type Position = { id: number; name: string; positionType: "Основна" | "Запасна" | "Облаштовується" | "Виявлена ворогом" | "Зайнята суміжниками"; stripName: string; locality: string; battleOrder: string; sector: string; condition: string; conditionLevel: number; fieldType: string; size: string; mgrs: string; suitableUavText: string; isActive: boolean; crewId: number | null; crewName: string | null; notes: string; uavIds: number[]; uavNames: string[] };
export type PositionDraft = Omit<Position, "id" | "crewName" | "uavNames">;
export type PositionWorkDuty = "Охорона та оборона" | "Рекогностування" | "Облаштування";
export type PositionWorkMember = { assignmentId: number | null; personnelId: number; fullName: string; rank: string; dutyType: PositionWorkDuty; startDate: string; startTime: string; endDate: string; endTime: string };
export type PositionWork = { id: number; positionId: number | null; positionName: string; stripName: string; locality: string; mgrs: string; workType: "Рекогностування" | "Облаштування"; status: "Приступили" | "Продовжують" | "Завершили"; startDate: string; startTime: string; endDate: string; endTime: string; battleOrder: string; notes: string; members: PositionWorkMember[] };
export type PositionWorkMemberDraft = Pick<PositionWorkMember, "personnelId" | "dutyType" | "startDate" | "startTime" | "endDate" | "endTime"> & { assignmentId?: number | null };
export type PositionWorkDraft = Omit<PositionWork, "id" | "members"> & { personnelIds: number[]; memberAssignments: PositionWorkMemberDraft[] };
export type PositionWorkStatusEvent = Omit<PositionWork, "id" | "locality" | "mgrs"> & { id: number; workId: number; positionMgrs: string; positionLocality: string; createdAt: string };
export type TemporaryPerson = { id: number; fullName: string; rank: string; position: string; actingSlotId: string; actingPosition: string; duties: string; arrivedAt: string; currentLocation: string; notes: string; category: "Тимчасово прибулі" | "Прикомандировані" | "Інша підгрупа"; groupName: string };
export type StaffingRecord = { isTemporary?: boolean; isExternal?: boolean; isCrewPlaceholder?: boolean; bcsGroupName?: string; bcsStructureKind?: string; bcsOrder?: number; personnelId: number; fullName: string; rank: string; position: string; workingStrength?: number; staffSlotId?: string; actingSlotId?: string; crewId: number | null; crewName: string | null; actualCrewId?: number | null; actualCrewName?: string | null; platoon: string; companyName: string; unitType: string; crewPositionName: string; battleOrder: string; sector: string; officialStrength: number; actualStrength: number; crewStatus: string; uavName: string; uavType: string; functionalDuties: string; currentLocation: string; bcsStatus: string; notes: string; actingPosition: string; recommendationCount: number };
export type StaffRecommendation = { id: number; personnelId: number; fullName: string; positionName: string; issuedAt: string; notes: string };
export type VacancyRecommendationDraft = {
  slotId?: string;
  positionName: string;
  candidateType: "Військовий" | "Цивільний";
  fullName: string;
  rank: string;
  taxId: string;
  birthDate: string;
  education: string;
  educationGraduationYear: string;
  armedForcesSince: string;
  combatParticipation: string;
  currentUnit: string;
  currentPosition: string;
  staffCategory: string;
  militarySpecialty: string;
  tariffGrade: string;
  salary: string;
  registrationAddress: string;
  residentialAddress: string;
  driverLicense: string;
  passport: string;
  phone: string;
  militaryId: string;
  serviceEntryType: string;
  serviceStartDate: string;
  serviceEndDate: string;
  conscriptionOffice: string;
  conscriptedAt: string;
  maritalStatus: string;
  relatives: string;
  issuedAt: string;
  notes: string;
};
export type VacancyRecommendation = VacancyRecommendationDraft & { id: number; slotId: string };
export type Equipment = {
  id: number;
  category: EquipmentCategory;
  name: string;
  inventoryNumber: string;
  status: string;
  crewId: number | null;
  crewName: string | null;
  personnelId: number | null;
  holderName: string | null;
  totalQuantity: number;
  dayQuantity: number;
  nightQuantity: number;
  uavType?: string;
  assetKind: "aircraft" | "complex";
  componentsJson: string;
  assignedQuantity: number;
  weaponKind: "weapon" | "ammunition" | "component";
  measurementUnit: string;
  stockQuantity: number;
  notes: string;
};
export type EquipmentDraft = Omit<Equipment, "id" | "crewName" | "holderName">;
export type AssetServiceCode = "zbbr" | "zu" | "gz_kb" | "siiz" | "ms" | "ets" | "ovtm" | "rs" | "sa_ppo" | "svt" | "pmm";
export type AssetCatalogField = { id: number; catalogId: number; fieldKey: string; displayName: string; fieldType: string; initialValue: string; sortOrder: number };
export type AssetCatalog = { id: number; serviceCode: AssetServiceCode; name: string; isSystem: boolean; sortOrder: number; fields: AssetCatalogField[] };
export type AssetCatalogDraft = { serviceCode: AssetServiceCode; name: string; fields: Array<Omit<AssetCatalogField, "id" | "catalogId">> };
export type ServiceAsset = {
  id: number;
  category: EquipmentCategory;
  serviceCode: AssetServiceCode;
  catalogId: number | null;
  catalogName: string | null;
  name: string;
  fullName: string;
  nomenclatureNumber: string;
  inventoryNumber: string;
  serialNumber: string;
  manufactureYear: string;
  accountingUnit: string;
  quantity: number;
  value: number;
  status: string;
  crewId: number | null;
  crewName: string | null;
  personnelId: number | null;
  holderName: string | null;
  parentEquipmentId: number | null;
  parentName: string | null;
  assetType: string;
  serviceData: Record<string, string>;
  customValues: Record<string, string>;
  notes: string;
  createdAt: string;
  updatedAt: string;
};
export type ServiceAssetDraft = Omit<ServiceAsset, "id" | "category" | "catalogName" | "crewName" | "holderName" | "parentName" | "createdAt" | "updatedAt">;
export type AssetHistoryEvent = { id: number; equipmentId: number | null; assetName: string; serviceCode: AssetServiceCode; eventType: string; quantityDelta: number; quantityAfter: number; fromHolder: string; toHolder: string; details: string; occurredAt: string };
export type AssetWriteOff = {
  id: number;
  incidentId: number | null;
  equipmentId: number | null;
  serviceCode: AssetServiceCode | "";
  incidentType: string;
  incidentOccurredAt: string;
  assetName: string;
  inventoryNumber: string;
  serialNumber: string;
  accountingUnit: string;
  quantity: number;
  status: string;
  notes: string;
  createdAt: string;
  updatedAt: string;
  completedAt: string;
};
export type AssetWriteOffHistoryEvent = { id: number; writeOffId: number; status: string; notes: string; createdAt: string };
export type WorkshopIngredient = { equipmentId: number; equipmentName: string; quantity: number; measurementUnit: string };
export type WorkshopProduct = { id: number; name: string; quantity: number; measurementUnit: string; ingredients: WorkshopIngredient[]; notes: string; createdAt: string };
export type WorkshopDraft = Omit<WorkshopProduct, "id" | "createdAt"> & { accountedAt: string };
export type IncidentStep = { id: number; order: number; title: string; description: string; required: boolean; status: string; dueAt: string; completedAt: string; comment: string; updatedAt: string };
export type IncidentDocument = { id: number; documentType: string; requirement?: string; actionKind?: "document" | "copy"; status: string; updatedAt: string };
export type IncidentHistoryEvent = { id: number; action: string; details: string; createdAt: string };
export type Incident = {
  id: number;
  category: string;
  incidentType: string;
  status: string;
  occurredAt: string;
  crewId: number | null;
  crewName: string | null;
  equipmentId: number | null;
  equipmentName: string | null;
  equipmentIds: number[];
  equipmentNames: string[];
  personnelIds: number[];
  personnelNames: string[];
  positionName: string;
  reconnaissanceArea: string;
  crewSnapshot: string;
  vehicleName: string;
  description: string;
  immediateActions: string;
  consequences: string;
  flightStage: string;
  preliminaryCause: string;
  snapshotSource: string;
  reportedTo: string;
  reportedAt: string;
  sourceFlightId: number | null;
  eventData: Record<string, unknown>;
  steps: IncidentStep[];
  documents: IncidentDocument[];
  history: IncidentHistoryEvent[];
};
export type IncidentDraft = Omit<Incident, "id" | "crewName" | "equipmentName" | "equipmentNames" | "personnelNames" | "crewSnapshot" | "vehicleName" | "steps" | "documents" | "history">;
export type IncidentDataDraft = Pick<Incident, "description" | "flightStage" | "preliminaryCause" | "eventData">;
export type FlightPlanWeather = { temperature: string; windFrom: string; windTo: string; gustFrom: string; gustTo: string; cloudiness: string; cloudHeight: string; precipitation: string };
export type FlightPlanUavSelection = { equipmentId: number; dayQuantity: number; nightQuantity: number };
export type FlightPlanPayloadSelection = { sourceType: "equipment" | "workshop"; sourceId: number };
export type FlightPlanUavSnapshot = { equipmentId: number; name: string; serialNumber: string };
export type FlightPlanMemberSnapshot = { personnelId: number; fullName: string; rank: string };
export type FlightPlanPersonnelTransition = {
  id: string;
  crewId: number;
  outgoingMemberIds: number[];
  outgoingTime: string;
  incomingMemberIds: number[];
  incomingTime: string;
  memberSnapshots?: FlightPlanMemberSnapshot[];
};
export type FlightPlanEntry = { crewId: number; actualMemberIds: number[]; actualCommanderId: number | null; actualVehicleId: number | null; withoutVehicle?: boolean; weather: FlightPlanWeather; routePoints: string[]; altitudeFrom: string; altitudeTo: string; areaPoints: string[]; task: string; startTime: string; endTime: string; uavSelections: FlightPlanUavSelection[]; payloadSelection: FlightPlanPayloadSelection | null; rotationId?: string; crewName?: string; crewUavType?: string; positionId?: number | null; positionName?: string; positionMgrs?: string; positionLocality?: string; workStrip?: string; battleOrder?: string; uavSnapshots?: FlightPlanUavSnapshot[]; memberSnapshots?: FlightPlanMemberSnapshot[]; arrivesToday?: boolean; departsToday?: boolean; departureTime?: string };
export type FlightPlanRotation = FlightPlanEntry & { rotationId: string };
export type FlightPlanCrewLocationAssignment = { crewId: number; stages: number[][]; arrivesToday?: boolean; departsToday?: boolean };
export type FlightPlanRequest = { unitName: string; entries: FlightPlanEntry[]; personnelTransitions?: FlightPlanPersonnelTransition[] };
export type FlightJournalEntry = {
  id: number;
  flightDate: string;
  skyTime: string;
  groundTime: string;
  completionType?: string;
  completionTime?: string;
  completionDetail?: string;
  crewId: number | null;
  crewName: string;
  positionId: number | null;
  positionName: string;
  battleOrder: string;
  workStrip: string;
  uavId: number | null;
  uavName: string;
  uavType: string;
  uavSerialNumber: string;
  mission: string;
  payloadSource: string;
  payloadId: number | null;
  payloadType: string;
  payloadSerialNumber: string;
  notes: string;
};
export type FlightJournalDraft = Omit<FlightJournalEntry, "id">;
