export type EquipmentCategory = "generator" | "uav" | "communications" | "weapon_ammo";

export type CrewMember = { personnelId: number; fullName: string; rank: string; position: string; callsign: string };
export type Crew = {
  id: number;
  name: string;
  platoon: string;
  positionName: string;
  reconnaissanceArea: string;
  unitType: string;
  companyName: string;
  battleOrder: string;
  sector: string;
  officialStrength: number;
  workingStrength: number;
  positionId: number | null;
  status: string;
  uavName: string;
  uavType: string;
  primaryUavId?: number | null;
  functionalDuties: string;
  currentLocation: string;
  notes: string;
  memberCount: number;
  members: CrewMember[];
  actualMembers: CrewMember[];
};
export type CrewDraft = {
  name: string;
  platoon: string;
  positionName: string;
  reconnaissanceArea: string;
  unitType: string;
  companyName: string;
  battleOrder: string;
  sector: string;
  officialStrength: number;
  workingStrength: number;
  positionId: number | null;
  status: string;
  uavName: string;
  uavType: string;
  primaryUavId?: number | null;
  functionalDuties: string;
  currentLocation: string;
  notes: string;
  memberIds: number[];
  actualMemberIds: number[];
};
export type Position = { id: number; name: string; positionType: "Основна" | "Запасна" | "Облаштовується" | "Виявлена ворогом" | "Зайнята суміжниками"; stripName: string; locality: string; battleOrder: string; sector: string; condition: string; conditionLevel: number; fieldType: string; size: string; mgrs: string; suitableUavText: string; isActive: boolean; crewId: number | null; crewName: string | null; notes: string; uavIds: number[]; uavNames: string[] };
export type PositionDraft = Omit<Position, "id" | "crewName" | "uavNames">;
export type TemporaryPerson = { id: number; fullName: string; rank: string; position: string; actingSlotId: string; actingPosition: string; duties: string; arrivedAt: string; currentLocation: string; notes: string; category: "Тимчасово прибулі" | "Прикомандировані" | "Інша підгрупа"; groupName: string };
export type StaffingRecord = { isTemporary?: boolean; isExternal?: boolean; isCrewPlaceholder?: boolean; bcsGroupName?: string; bcsStructureKind?: string; bcsOrder?: number; personnelId: number; fullName: string; rank: string; position: string; workingStrength?: number; staffSlotId?: string; actingSlotId?: string; crewId: number | null; crewName: string | null; platoon: string; companyName: string; unitType: string; crewPositionName: string; battleOrder: string; sector: string; officialStrength: number; actualStrength: number; crewStatus: string; uavName: string; uavType: string; functionalDuties: string; currentLocation: string; bcsStatus: string; notes: string; actingPosition: string; recommendationCount: number };
export type StaffRecommendation = { id: number; personnelId: number; fullName: string; positionName: string; issuedAt: string; notes: string };
export type VacancyRecommendation = { id: number; slotId?: string; positionName: string; fullName: string; phone: string; rank: string; birthDate: string; issuedAt: string; notes: string };
export type Equipment = {
  id: number;
  category: EquipmentCategory;
  name: string;
  inventoryNumber: string;
  status: string;
  crewId: number | null;
  crewName: string | null;
  personnelId: number | null;
  holderName: string | null;
  totalQuantity: number;
  dayQuantity: number;
  nightQuantity: number;
  uavType?: string;
  assetKind: "aircraft" | "complex";
  componentsJson: string;
  assignedQuantity: number;
  notes: string;
};
export type EquipmentDraft = Omit<Equipment, "id" | "crewName" | "holderName">;
export type Incident = {
  id: number;
  incidentType: string;
  occurredAt: string;
  crewId: number | null;
  crewName: string | null;
  equipmentId: number | null;
  equipmentName: string | null;
  positionName: string;
  reconnaissanceArea: string;
  crewSnapshot: string;
  vehicleName: string;
  description: string;
};
export type IncidentDraft = Omit<Incident, "id" | "crewName" | "equipmentName" | "crewSnapshot" | "vehicleName">;
export type FlightPlanWeather = { temperature: string; windFrom: string; windTo: string; gustFrom: string; gustTo: string; cloudiness: string; cloudHeight: string; precipitation: string };
export type FlightPlanUavSelection = { equipmentId: number; dayQuantity: number; nightQuantity: number };
export type FlightPlanEntry = { crewId: number; weather: FlightPlanWeather; routePoints: string[]; altitudeFrom: string; altitudeTo: string; areaPoints: string[]; task: string; startTime: string; endTime: string; uavSelections: FlightPlanUavSelection[] };
export type FlightPlanRequest = { unitName: string; entries: FlightPlanEntry[] };
