export type EquipmentCategory = "generator" | "uav" | "communications" | "weapon_ammo";

export type CrewMember = { personnelId: number; fullName: string; rank: string; position: string };
export type Crew = {
  id: number;
  name: string;
  platoon: string;
  positionName: string;
  reconnaissanceArea: string;
  unitType: string;
  companyName: string;
  battleOrder: string;
  sector: string;
  officialStrength: number;
  status: string;
  uavName: string;
  uavType: string;
  functionalDuties: string;
  currentLocation: string;
  notes: string;
  memberCount: number;
  members: CrewMember[];
};
export type CrewDraft = {
  name: string;
  platoon: string;
  positionName: string;
  reconnaissanceArea: string;
  unitType: string;
  companyName: string;
  battleOrder: string;
  sector: string;
  officialStrength: number;
  status: string;
  uavName: string;
  uavType: string;
  functionalDuties: string;
  currentLocation: string;
  notes: string;
  memberIds: number[];
};
export type Position = { id: number; name: string; positionType: "Основна" | "Запасна" | "В облаштуванні"; stripName: string; locality: string; battleOrder: string; sector: string; condition: string; size: string; mgrs: string; suitableUavText: string; isActive: boolean; crewId: number | null; crewName: string | null; notes: string; uavIds: number[]; uavNames: string[] };
export type PositionDraft = Omit<Position, "id" | "crewName" | "uavNames">;
export type StaffingRecord = { personnelId: number; fullName: string; rank: string; position: string; crewId: number | null; crewName: string | null; platoon: string; companyName: string; unitType: string; crewPositionName: string; battleOrder: string; sector: string; officialStrength: number; actualStrength: number; crewStatus: string; uavName: string; uavType: string; functionalDuties: string; currentLocation: string; bcsStatus: string; notes: string; actingPosition: string; recommendationCount: number };
export type StaffRecommendation = { id: number; personnelId: number; fullName: string; positionName: string; issuedAt: string; notes: string };
export type VacancyRecommendation = { id: number; positionName: string; fullName: string; phone: string; rank: string; birthDate: string; issuedAt: string; notes: string };
export type Equipment = {
  id: number;
  category: EquipmentCategory;
  name: string;
  inventoryNumber: string;
  status: string;
  crewId: number | null;
  crewName: string | null;
  personnelId: number | null;
  holderName: string | null;
  notes: string;
};
export type EquipmentDraft = Omit<Equipment, "id" | "crewName" | "holderName">;
export type Incident = {
  id: number;
  incidentType: string;
  occurredAt: string;
  crewId: number | null;
  crewName: string | null;
  equipmentId: number | null;
  equipmentName: string | null;
  positionName: string;
  reconnaissanceArea: string;
  crewSnapshot: string;
  vehicleName: string;
  description: string;
};
export type IncidentDraft = Omit<Incident, "id" | "crewName" | "equipmentName" | "crewSnapshot" | "vehicleName">;
